// src/core/arena.ts
//
// Story jt1-4 (GREEN, Julia) — GENERATED by tools/transcribe-arena.mjs from the
// vendored 1982 Williams source. DO NOT HAND-EDIT.
//
// The arena: where an entity may be, what it lands on, and what kills it. This
// is the epic's first real simulation logic, so it is CORE — pure functions over
// plain numbers, no clock, no entropy, no browser surface, no shell import.
//
// ─── POSITION UNITS: X AND Y ARE NOT THE SAME FORMAT ─────────────────────────
// The two axes use DIFFERENT representations, and flattening them into one
// sentence is worse than saying nothing — the next author trusts it and
// symmetrises, which is the natural assumption and silently wrong.
//
//   Y is 16-bit pixel+fraction (8.8): 256 units = one pixel, whole pixel in the
//   high byte (ADDD PPOSY+1,U — JOUSTRV4.SRC:6494). The ROM compares only that
//   HIGH byte against CEILNG and FLOOR (CMPA #CEILNG), so every threshold below
//   is a WHOLE-PIXEL test on pos >> 8; comparing the full 16-bit value would be
//   wrong by up to a pixel at every boundary. applyCeiling and isLavaDeath take
//   Y in this form.
//
//   X is a 16-bit signed WHOLE-PIXEL count. Its sub-pixel accumulator lives in
//   the VELOCITY (ADDB PVELX+2,U / ADCA #0 — :6514-6516), not in the position,
//   so only whole pixels ever reach PPOSX. wrapX therefore takes and returns
//   whole-pixel X, and a fractional X is a caller bug rather than a value to
//   round silently.
//
// ─── DOMAIN: TOTAL INSIDE, THROWING OUTSIDE ──────────────────────────────────
// Every function here is total over its documented domain and THROWS outside
// it. The alternative — letting a NaN through — is far worse in a deterministic
// sim: it propagates for thousands of frames and surfaces as an unreproducible
// trajectory instead of a stack trace at the call that caused it.
//
// ─── FIVE LAWS THAT ARE NOT WHAT THEY LOOK LIKE ──────────────────────────────
// Each was verified against the source before it was written here; the story's
// original prose had all five differently.
//   1. The X wrap is NOT a modulus (see wrapX).
//   2. The ceiling CLAMPS position and negates velocity only when ascending.
//   3. CLIF5's landing mask is $A0, tested with BITA — not a bare $20.
//   4. The landing dispatch has SEVEN outcomes; the seventh is the lava troll.
//   5. LNDB2's author comment names the wrong cliff; its constant is right.
//
// ─── jt3-1 RETROFIT (user ruling A) ──────────────────────────────────────────
// lavaLevelForWave now DELEGATES to the centralized difficulty engine (the IWAVE
// inter-wave pass, src/core/difficulty.ts) — the lava step is one of the other
// per-wave knobs computed in that same pass. The LAVA_START/MIN/STEP constants
// below remain arena's cited data (the engine imports them); only the FUNCTION's
// SOURCE moved. The realized value is bit-for-bit unchanged (the jt2-1 migration
// bar). This is the one sanctioned hand-edit to this generated file.

import { lavaLevelForWave as difficultyLava } from './difficulty.js'

/** Where a constant came from: an inclusive line range in a vendored file. */
export interface SourceAnchor {
  file: string
  startLine: number
  endLine: number
}

/**
 * One landing surface. `bandTop`..`bandTop+bandHeight-1` are the scanlines
 * LNDYTB marks for it; `snapY` is the whole-pixel Y the entity is placed at.
 * Every band is 4 scanlines and every snapY is `bandTop - 1` — the entity rests
 * one pixel ABOVE the surface it stands on.
 */
export interface Platform {
  /** LNDXTB/LNDYTB mask bit. */
  bit: number
  snapY: number
  bandTop: number
  bandHeight: number
  /** Cliff records this surface belongs to, by jt1-3 label. Frozen: flight.ts
   * reads PLATFORMS every frame and an accidental write would corrupt every
   * subsequent entity silently, breaking determinism WITHIN a run. */
  cliffs: readonly string[]
  anchor: SourceAnchor
}

/** What CKGND's dispatch decides for a given mask value. */
export type GroundOutcome =
  | { kind: 'airborne' }
  | { kind: 'platform'; platform: Platform }
  /** LNDB7 — the lava troll's grip, gated on TTROLL. Behaviour lands in jt3. */
  | { kind: 'troll' }

/** One entry of the BCKCOL cliff-side collision path. */
export interface BackgroundSurface {
  /** BCKXTB/BCKYTB mask bit — NOT the landing table's assignment. */
  bit: number
  cliff: string
  /** `LDD #n` — the X origin the span walk starts from. */
  originX: number
  /** `LDX #n` — the cliff's top scanline. */
  originY: number
  /** jt1-3 collision-table label reached via `LDY [cliff]`. */
  collisionTable: string
  anchor: SourceAnchor
}

// ─── Bounds (JOUSTRV4.SRC:36-39) ────────────────────────────────────────────

/** `CEILNG EQU $0020` — highest position in the game. HEX. */
export const CEILING = 0x20
/** `FLOOR EQU $00DF` — lowest position in the game. HEX. */
export const FLOOR = 0xdf
/** `ELEFT EQU -10` — extreme left of the wrap-around screen. DECIMAL. */
export const ELEFT = -10
/** `ERIGHT EQU 292` — extreme right of the wrap-around screen. DECIMAL. */
export const ERIGHT = 292

/**
 * `ERIGHT-ELEFT+1` = 303, the correction step WRAPX applies at most once
 * in each direction. Derived from the bounds, never stated independently.
 */
export const WRAP_SPAN = ERIGHT - ELEFT + 1

/**
 * `CMPA #FLOOR+7` (JOUSTRV4.SRC:6508) — at or below this whole-pixel Y the
 * entity is swimming in the lava and dies.
 */
export const DEATH_Y = FLOOR + 7

// ─── Lava + bridge (JOUSTRV4.SRC:954-962, 1929-1933) ────────────────────────

/** `LDA #$EA / STA SAFRAM` (:962-963) — the wave-1 lava surface. HEX. */
export const LAVA_START = 0xea
/** `CMPA #$E0 / BLS` (:1930-1931) — the lava stops rising here. HEX. */
export const LAVA_MIN = 0xe0
/** `SUBA #$5` (:1932) — one step per wave. Rising lava means DEcreasing Y. */
export const LAVA_STEP = 5
/** `LDA #3 / STA TBRIDGE` (:954-955) — the wave that burns the bridge. DECIMAL. */
export const BRIDGE_WAVE = 3
/** `LDA #1 / STA TTROLL` (:956-957) — waves after the bridge until the troll. DECIMAL. */
export const TROLL_DELAY = 1

// ─── The six landing surfaces (LNDB0..LNDB5, JOUSTRV4.SRC:6728-6762) ────────

export const PLATFORMS: readonly Platform[] = Object.freeze([
  // LNDB0 — CLIF1L & CLIF1R. `LDB #$0045-1`
  Object.freeze({ bit: 0x01, snapY: 68, bandTop: 69, bandHeight: 4, cliffs: Object.freeze(['CLIF1L', 'CLIF1R']), anchor: { file: 'JOUSTRV4.SRC', startLine: 6729, endLine: 6729 } }),
  // LNDB1 — CLIF2. `LDB #$0051-1`
  Object.freeze({ bit: 0x02, snapY: 80, bandTop: 81, bandHeight: 4, cliffs: Object.freeze(['CLIF2']), anchor: { file: 'JOUSTRV4.SRC', startLine: 6735, endLine: 6735 } }),
  // LNDB2 — CLIF3U. `LDB #$0081-1`
  // (the author comment here reads CLIF3R; the constant is CLIF3U's band — follow the constant)
  Object.freeze({ bit: 0x04, snapY: 128, bandTop: 129, bandHeight: 4, cliffs: Object.freeze(['CLIF3U']), anchor: { file: 'JOUSTRV4.SRC', startLine: 6741, endLine: 6741 } }),
  // LNDB3 — CLIF3L & CLIF3R. `LDB #$008A-1`
  Object.freeze({ bit: 0x08, snapY: 137, bandTop: 138, bandHeight: 4, cliffs: Object.freeze(['CLIF3L', 'CLIF3R']), anchor: { file: 'JOUSTRV4.SRC', startLine: 6747, endLine: 6747 } }),
  // LNDB4 — CLIF4. `LDB #$00A3-1`
  Object.freeze({ bit: 0x10, snapY: 162, bandTop: 163, bandHeight: 4, cliffs: Object.freeze(['CLIF4']), anchor: { file: 'JOUSTRV4.SRC', startLine: 6753, endLine: 6753 } }),
  // LNDB5 — CLIF5. `LDB #$00D3-1`
  Object.freeze({ bit: 0x20, snapY: 210, bandTop: 211, bandHeight: 17, cliffs: Object.freeze(['CLIF5']), anchor: { file: 'JOUSTRV4.SRC', startLine: 6759, endLine: 6759 } }),
])

// ─── The eight BCKCOL cliff-side surfaces (JOUSTRV4.SRC:6799-6921) ──────────
//
// open-questions §4 asked how far this path could be traced. All the way:
// BCKXTB/BCKYTB is a box broad-phase; on a hit BCKCOL dispatches on the mask,
// dereferences that cliff record's collision-span pointer (`LDY [CLIF1L]` — the
// tables jt1-3 transcribed) and walks it from an (originX, originY) origin.
//
// THE TRAP: this bit assignment is NOT the landing table's. Eight bits with
// left/right separate here, six with the pairs merged there. Bit 4 is CLIF3L
// here and CLIF4 there.

export const BACKGROUND_SURFACES: readonly BackgroundSurface[] = Object.freeze([
  Object.freeze({ bit: 0x01, cliff: 'CLIF1L', originX: -32, originY: 69, collisionTable: 'CCLF1L', anchor: { file: 'JOUSTRV4.SRC', startLine: 6817, endLine: 6821 } }),
  Object.freeze({ bit: 0x02, cliff: 'CLIF1R', originX: 252, originY: 69, collisionTable: 'CCLF1R', anchor: { file: 'JOUSTRV4.SRC', startLine: 6856, endLine: 6860 } }),
  Object.freeze({ bit: 0x04, cliff: 'CLIF2', originX: 86, originY: 81, collisionTable: 'CCLF2', anchor: { file: 'JOUSTRV4.SRC', startLine: 6909, endLine: 6913 } }),
  Object.freeze({ bit: 0x08, cliff: 'CLIF3U', originX: 202, originY: 129, collisionTable: 'CCLF3R', anchor: { file: 'JOUSTRV4.SRC', startLine: 6873, endLine: 6876 } }),
  Object.freeze({ bit: 0x10, cliff: 'CLIF3L', originX: -32, originY: 138, collisionTable: 'CCLF3L', anchor: { file: 'JOUSTRV4.SRC', startLine: 6823, endLine: 6826 } }),
  Object.freeze({ bit: 0x20, cliff: 'CLIF3R', originX: 202, originY: 129, collisionTable: 'CCLF3R', anchor: { file: 'JOUSTRV4.SRC', startLine: 6862, endLine: 6865 } }),
  Object.freeze({ bit: 0x40, cliff: 'CLIF4', originX: 106, originY: 163, collisionTable: 'CCLF4', anchor: { file: 'JOUSTRV4.SRC', startLine: 6918, endLine: 6921 } }),
  Object.freeze({ bit: 0x80, cliff: 'CLIF5', originX: 54, originY: 211, collisionTable: 'CCLF5', anchor: { file: 'JOUSTRV4.SRC', startLine: 6903, endLine: 6906 } }),
])

// ─── The scanline maps ──────────────────────────────────────────────────────

/** LNDYTB (JOUSTRV4.SRC:7719+) — one landing mask byte per scanline. */
export const LND_Y_TABLE: readonly number[] = Object.freeze([
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
  0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 4, 4, 4, 4, 0, 0, 0, 0, 0, 8, 8, 8, 8, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 16, 16, 16, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 128, 128, 128, 128,
  128, 128, 128, 160, 160, 160, 160, 160, 160, 160, 160, 160, 160, 160, 160, 160,
  160, 160, 160, 160, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
])

/** BCKYTB (JOUSTRV4.SRC:7549+) — the SEPARATE background-collision map. */
export const BCK_Y_TABLE: readonly number[] = Object.freeze([
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3,
  3, 3, 3, 3, 3, 3, 3, 7, 7, 7, 7, 7, 7, 7, 7, 4,
  4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 8, 8, 8, 8, 8, 8, 8, 8, 8,
  56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 48,
  48, 48, 48, 48, 16, 0, 0, 0, 0, 64, 64, 64, 64, 64, 64, 64,
  64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 128, 128, 128, 128, 128, 128,
  128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
])

// ─── Laws ───────────────────────────────────────────────────────────────────

/**
 * WRAPX (JOUSTRV4.SRC:7290-7298).
 *
 * ONE conditional subtract, then ONE conditional add — deliberately NOT a
 * modulus. `CMPD #ERIGHT / BLE` skips the subtract when x is in range, and
 * `CMPD #ELEFT / BGE` skips the add. Both comparisons are inclusive, so the
 * bounds themselves are legal positions.
 *
 * For every velocity the game can produce (`MAXVX EQU 8`, :40) this agrees with
 * `((x - ELEFT) mod 303) + ELEFT`, which is exactly why writing the modulus
 * would ship green. They diverge on large deltas, where the ROM applies its one
 * correction and stops — leaving x legally outside the range (600 -> 297, not -6).
 */
export function wrapX(x: number): number {
  // X is a WHOLE-PIXEL count — see the header. A fractional or NaN X is a
  // caller bug, and a deterministic sim must hear about it here rather than
  // thousands of frames later as an unreproducible trajectory.
  if (!Number.isInteger(x)) throw new TypeError(`wrapX expects a whole-pixel X, got ${x}`)
  let r = x
  if (r > ERIGHT) r -= WRAP_SPAN
  if (r < ELEFT) r += WRAP_SPAN
  return r
}

/**
 * The ceiling half of ADDGRX (JOUSTRV4.SRC:6497-6506).
 *
 * `CMPA #CEILNG / BHI ADGCEI` — nothing happens while the whole-pixel Y is
 * strictly above (numerically greater than) the ceiling. On contact:
 *   - `LDD PVELY / BPL ADGDWN` negates velocity ONLY when it is already upward.
 *     An entity descending through the band keeps its velocity; flipping it
 *     would fling it back up and trap it.
 *   - `COMA / NEGB / SBCA #-1` is exact 16-bit two's-complement negation —
 *     elastic means elastic, with no damping.
 *   - `ADGDWN LDD #CEILNG*256` runs unconditionally, so position is CLAMPED to
 *     exactly CEILING<<8 with the fraction zeroed, however far past the ceiling
 *     the step went. Mirroring the overshoot instead drifts from the ROM within
 *     a single frame.
 */
export function applyCeiling(
  posY: number,
  velY: number,
): { posY: number; velY: number; bumped: boolean } {
  if (!Number.isInteger(posY)) throw new TypeError(`applyCeiling posY must be an integer, got ${posY}`)
  if (!Number.isInteger(velY)) throw new TypeError(`applyCeiling velY must be an integer, got ${velY}`)
  if (posY >> 8 > CEILING) return { posY, velY, bumped: false }
  // Only when ascending, and wrapped to 16 bits so the negation is the 6809's.
  const velOut = velY < 0 ? ((-velY << 16) >> 16) : velY
  return { posY: CEILING << 8, velY: velOut, bumped: true }
}

/**
 * ADGCEI (JOUSTRV4.SRC:6508-6509): `CMPA #FLOOR+7 / BHS ADGFLR`. Unsigned
 * higher-or-same on the HIGH byte, so the test is at-or-below on whole pixels
 * and a deep fraction one pixel short does not kill.
 */
export function isLavaDeath(posY: number): boolean {
  if (!Number.isInteger(posY)) throw new TypeError(`isLavaDeath posY must be an integer, got ${posY}`)
  return (posY >> 8) >= DEATH_Y
}

const platformByBit = (bit: number): Platform => {
  const p = PLATFORMS.find((q) => q.bit === bit)
  if (!p) throw new Error(`no platform for bit ${bit}`)
  return p
}

/**
 * CKGND's dispatch (JOUSTRV4.SRC:6715-6726), branch for branch:
 *
 *   LND18  CMPA #$08 / BLO LND13 / BEQ LNDB3
 *   LND47  CMPA #$20 / BLO LNDB4 / BITA #$20 / BNE LNDB5 / BRA LNDB7
 *   LND13  CMPA #$02 / BEQ LNDB1 / BHI LNDB2   (falls through to LNDB0)
 *
 * Note the last step is a BIT test, not equality: LNDYTB never holds a bare
 * $20 — CLIF5's band is $A0 (bit 7 | bit 5). A dispatch written as
 * bit-per-platform equality misses CLIF5 entirely and drops entities through
 * the bottom island. Bit 7 WITHOUT bit 5 is the lava troll.
 */
export function groundOutcome(mask: number): GroundOutcome {
  // The mask is one byte, produced by ANDing the X and Y maps. Anything else is
  // a caller bug, including the 256/-1 off-by-one at the ends of the range.
  if (!Number.isInteger(mask) || mask < 0 || mask > 0xff) {
    throw new RangeError(`groundOutcome expects a byte mask 0..255, got ${mask}`)
  }
  const a = mask & 0xff
  if (a === 0) return { kind: 'airborne' }
  if (a < 0x08) {
    // LND13
    if (a === 0x02) return { kind: 'platform', platform: platformByBit(0x02) }
    if (a > 0x02) return { kind: 'platform', platform: platformByBit(0x04) }
    return { kind: 'platform', platform: platformByBit(0x01) }
  }
  if (a === 0x08) return { kind: 'platform', platform: platformByBit(0x08) }
  // LND47
  if (a < 0x20) return { kind: 'platform', platform: platformByBit(0x10) }
  if (a & 0x20) return { kind: 'platform', platform: platformByBit(0x20) }
  return { kind: 'troll' }
}

/**
 * LNDBn (JOUSTRV4.SRC:6728-6762): `LDB #$xx-1 / STB PPOSY+1,U / CLRA`.
 *
 * Landing is a SNAP, not a resolve. The whole-pixel Y is ASSIGNED and the
 * fraction is cleared, so nothing about the entry position or velocity
 * survives — which is what makes it idempotent. Vertical motion stops.
 */
export function land(platform: Platform): { posY: number; velY: number } {
  return { posY: platform.snapY << 8, velY: 0 }
}

/**
 * SAFRAM's per-wave rise (JOUSTRV4.SRC:1929-1933): `CMPA #$E0 / BLS / SUBA #$5`.
 *
 * A five-unit step with a hard floor, not a two-value range: $EA, $E5, $E0,
 * then it holds forever. Rising lava means DEcreasing Y, so the sequence is
 * monotonically non-increasing.
 *
 * jt3-1 retrofit (user ruling A): the value is now SOURCED from the centralized
 * difficulty engine — the same IWAVE inter-wave pass this lava step lives in —
 * not computed here. The realized value is bit-for-bit unchanged.
 */
export function lavaLevelForWave(wave: number): number {
  return difficultyLava(wave)
}

/**
 * TBRIDGE (JOUSTRV4.SRC:954-955, 1934-1936) is a countdown seeded at 3 and
 * decremented once per wave; the bridge burns when it reaches zero and stays
 * gone. The HOOK is this story's scope — what the destruction looks like is
 * jt3's.
 */
export function bridgeDestroyedOnWave(wave: number): boolean {
  return wave >= BRIDGE_WAVE
}
