// src/core/flight.ts
//
// Story jt1-5 (GREEN, Julia) — GENERATED by tools/transcribe-flight.mjs from the
// vendored 1982 Williams source. DO NOT HAND-EDIT.
//
// The flight and ground model — the epic's payload. CORE: pure functions over
// plain numbers, no clock, no entropy, no browser surface, no shell import, and
// every function is a pure transform of the state handed in (AC-3 determinism
// depends on it).
//
// ─── TWO POSITION FORMATS, DELIBERATELY NOT SYMMETRIC ────────────────────────
// This is the trap that produces a plausible, wrong implementation:
//
//   Y is 8.8 fixed point — whole pixel in the high byte, fraction in the low
//   (`ADDD PPOSY+1,U`, JOUSTRV4.SRC:6494). `posY >> 8` is the pixel.
//
//   X is a 16-bit SIGNED WHOLE-PIXEL count. Its sub-pixel accumulator lives in
//   the VELOCITY (`ADDB PVELX+2,U / ADCA #0`, :6514-6516) — `velXFrac` here —
//   and only the carry reaches the position. `posX` is already a pixel.
//
// Making both 8.8 is the natural symmetry assumption. It is wrong, and it is
// why arena.wrapX takes whole pixels while arena.applyCeiling takes 8.8.
//
// ─── THE FLYX LADDER IS INDEXED FROM ITS MIDDLE ──────────────────────────────
// In the ROM the `FLYX` label sits on the ZERO entry with four entries BEFORE
// it (:7150-7153), and the index is signed: `LDA PVELX,U / LDD A,X` with
// X = #FLYX reads backwards for a negative index. The array below is stored in
// index order −8..+8, so the ladder rung for index i is `FLYX[i / 2 + 4]`.
// Storing nine entries forward from the label would be wrong for every leftward
// flight. (LNDXS3 is the same zero-point-label shape — a house convention.)

import { LND_Y_TABLE } from './arena.js'

/** Where a constant came from: an inclusive line range in a vendored file. */
export interface SourceAnchor {
  file: string
  startLine: number
  endLine: number
}

/**
 * The device-agnostic per-player input contract (`P2NJMP`, JOUSTRV4.SRC:7261-7263).
 *
 * The ROM normalises two joystick bits with `ANDA #$03 / ASRA / SBCA #0`,
 * mapping raw 0→0, 1→−1, 2→+1 and — notably — 3→0: BOTH directions held is
 * neutral, not "last pressed wins". `flap` is the release→press EDGE; the shell
 * owns debouncing, core sees only the edge.
 */
export interface PlayerInput {
  dir: -1 | 0 | 1
  flap: boolean
  flapHeld: boolean
}

/** An entity's flight/ground state. Positions per the note above. */
export interface EntityState {
  posX: number
  posY: number
  velXIndex: number
  velXFrac: number
  velY: number
  timeUp: number
  groundState: string | null
  plantZ: number
  airborne: boolean
  /**
   * `PFRAME` — the run-animation phase, cycling 4 -> 3 -> 2 -> 1 -> 4
   * (`RUNR`, :7191-7196). `ORRUN_DELTAS` is indexed BY this, which is what
   * makes the gait uneven (3,2,1,2 px). Without it there is nothing to index by,
   * and a constant delta is the signature of a stub.
   */
  animPhase?: number
}

/** One row of the ground state machine (the `STATE` macro, :7160-7180). */
export interface GroundState {
  id: string
  wait: number
  call: string
  onMinus: string
  onZero: string
  onPlus: string
  flyVel: number
  anchor: SourceAnchor
}

// ─── Constants ──────────────────────────────────────────────────────────────

/** `LDA #4 / STA GRAV` (JOUSTRV4.SRC:952-953). DECIMAL. The BASE of the pair. */
export const GRAV = 4
/** Flap button HELD — `CLRB`, no offset (:6170). This is the glide. */
export const GRAVITY_WINGS_DOWN = GRAV
/** Flap button RELEASED — `LDB #$04` offset (:6197). HEX offset, decimal sum. */
export const GRAVITY_WINGS_UP = GRAV + 4
/** `MAXVX EQU 8` (:40). DECIMAL. The FLYX index bound — see flap()'s rejection note. */
export const MAX_VEL_X_INDEX = 8
/** `LDD #-$0080` (`STFLY`, :6124). HEX. Initial VY on a flap takeoff. */
export const TAKEOFF_VEL_Y = -0x0080
/** `ORRUN` per-frame X deltas, the second FCB operand of each row (:7185-7189). DECIMAL. */
export const ORRUN_DELTAS: readonly number[] = Object.freeze([0, 3, 2, 1, 2])
/** `LDD #SKID*256+2` (:7242) — the skid frame's X delta. DECIMAL. */
export const SKID_DELTA = 2
/** `LDB #2 / STB PLANTZ,U` (:6071-6072) — a skidding mount sits 2px lower. jt2 consumes it. */
export const SKID_PLANT_Z = 2

/**
 * The nine FLYX entries in INDEX order −8..+8 (:7150-7158). 256 units = 1 px/frame,
 * so the ladder is ±{2.0, 1.0, 0.5, 0.25, 0}. HEX in the source, signed 16-bit.
 * Index i maps to `FLYX[i / 2 + 4]` — zero is in the MIDDLE, not at the start.
 */
export const FLYX: readonly number[] = Object.freeze([-0x0200, -0x0100, -0x0080, -0x0040, 0x0000, 0x0040, 0x0080, 0x0100, 0x0200])

/** `FRCONV` (:6253-6257) — landing speed selects the ground state. */
export const FRCONV: readonly string[] = Object.freeze(['PLYBR', 'PLYCR', 'PLYDR', 'PLYER', 'PLYFR'])

/** The ground state machine (`STATE` rows, :7163-7175). */
export const GROUND_STATES: Readonly<Record<string, GroundState>> = Object.freeze({
  PLYAR: Object.freeze({ id: 'PLYAR', wait: 8, call: 'REVR', onMinus: 'PLYBR', onZero: 'PLYBR', onPlus: 'PLYBR', flyVel: 0, anchor: { file: 'JOUSTRV4.SRC', startLine: 7163, endLine: 7163 } }),
  PLYBR: Object.freeze({ id: 'PLYBR', wait: 0, call: 'STANDR', onMinus: 'PLYAR', onZero: 'PLYBR', onPlus: 'PLYCR', flyVel: 0, anchor: { file: 'JOUSTRV4.SRC', startLine: 7164, endLine: 7164 } }),
  PLYCR: Object.freeze({ id: 'PLYCR', wait: 8, call: 'RUNR', onMinus: 'PLYGR', onZero: 'PLYCR', onPlus: 'PLYDR', flyVel: 2, anchor: { file: 'JOUSTRV4.SRC', startLine: 7165, endLine: 7165 } }),
  PLYDR: Object.freeze({ id: 'PLYDR', wait: 4, call: 'RUNR', onMinus: 'PLYCR', onZero: 'PLYDR', onPlus: 'PLYER', flyVel: 4, anchor: { file: 'JOUSTRV4.SRC', startLine: 7166, endLine: 7166 } }),
  PLYER: Object.freeze({ id: 'PLYER', wait: 2, call: 'RUNR', onMinus: 'PLYHR', onZero: 'PLYER', onPlus: 'PLYFR', flyVel: 6, anchor: { file: 'JOUSTRV4.SRC', startLine: 7167, endLine: 7167 } }),
  PLYFR: Object.freeze({ id: 'PLYFR', wait: 1, call: 'RUNR', onMinus: 'PLYIR', onZero: 'PLYFR', onPlus: 'PLYFR', flyVel: 8, anchor: { file: 'JOUSTRV4.SRC', startLine: 7168, endLine: 7168 } }),
  PLYGR: Object.freeze({ id: 'PLYGR', wait: 2, call: 'RUNSR', onMinus: 'PLYBR', onZero: 'PLYBR', onPlus: 'PLYCR', flyVel: 2, anchor: { file: 'JOUSTRV4.SRC', startLine: 7169, endLine: 7169 } }),
  PLYHR: Object.freeze({ id: 'PLYHR', wait: 2, call: 'SKIDR', onMinus: 'PLYKR', onZero: 'PLYKR', onPlus: 'PLYDR', flyVel: 4, anchor: { file: 'JOUSTRV4.SRC', startLine: 7170, endLine: 7170 } }),
  PLYIR: Object.freeze({ id: 'PLYIR', wait: 2, call: 'SKIDR', onMinus: 'PLYJR', onZero: 'PLYJR', onPlus: 'PLYER', flyVel: 6, anchor: { file: 'JOUSTRV4.SRC', startLine: 7171, endLine: 7171 } }),
  PLYJR: Object.freeze({ id: 'PLYJR', wait: 2, call: 'SKIDR', onMinus: 'PLYKR', onZero: 'PLYKR', onPlus: 'PLYDR', flyVel: 4, anchor: { file: 'JOUSTRV4.SRC', startLine: 7172, endLine: 7172 } }),
  PLYKR: Object.freeze({ id: 'PLYKR', wait: 2, call: 'SKIDR', onMinus: 'PLYLR', onZero: 'PLYLR', onPlus: 'PLYDR', flyVel: 4, anchor: { file: 'JOUSTRV4.SRC', startLine: 7173, endLine: 7173 } }),
  PLYLR: Object.freeze({ id: 'PLYLR', wait: 4, call: 'SKIDR', onMinus: 'PLYMR', onZero: 'PLYMR', onPlus: 'PLYCR', flyVel: 2, anchor: { file: 'JOUSTRV4.SRC', startLine: 7174, endLine: 7174 } }),
  PLYMR: Object.freeze({ id: 'PLYMR', wait: 4, call: 'SKIDR', onMinus: 'PLYBR', onZero: 'PLYBR', onPlus: 'PLYCR', flyVel: 2, anchor: { file: 'JOUSTRV4.SRC', startLine: 7175, endLine: 7175 } }),
})

// ─── The landing / background X maps ────────────────────────────────────────
//
// `LNDXS1` (:7787) is ONE contiguous 352-byte table covering CRT pixel −$20
// through $13F — NOT a family of per-wave variants. `LNDXS3` (:7799) is a LABEL
// INTO it at the zero point (the same shape as FLYX) and `LNDXS2` (:7879) is the
// END MARKER. Confirmed by the RAM declarations: `LNDXD1` $20 + `LNDXTB` $140
// = 352 bytes exactly (RAMDEF.SRC:376-378).
//
// The per-wave variance lives entirely in RAM mutation, not in the ROM table:
// the wave init below, and a per-cliff create/destroy read-modify-write
// (:2341-2352) that is wave-machine scope and only ever REMOVES bits — so
// nothing transcribed here becomes wrong when that lands.

/** The index origin: `LND_X_TABLE[x + X_TABLE_ORIGIN]` is the mask for pixel x. */
export const X_TABLE_ORIGIN = 32

/** ROM `LNDXS1` (:7788+), 352 bytes, index 0 = CRT pixel −32. */
export const LND_X_TABLE: readonly number[] = Object.freeze([
  137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137,
  137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137,
  137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137,
  137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 136, 136, 136, 136, 136,
  136, 136, 136, 136, 136, 136, 136, 8, 8, 8, 8, 8, 8, 40, 40, 40,
  40, 40, 40, 40, 40, 40, 40, 40, 40, 32, 32, 32, 32, 32, 32, 32,
  32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 34, 34, 34,
  34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
  34, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
  50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
  50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
  50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
  50, 34, 34, 34, 34, 34, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
  32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
  32, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36,
  36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36,
  36, 36, 36, 36, 36, 36, 36, 4, 4, 4, 4, 4, 4, 4, 4, 132,
  132, 140, 140, 140, 141, 141, 141, 141, 141, 141, 141, 141, 137, 137, 137, 137,
  137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137,
  137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137,
  137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137,
  137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137, 137,
])

/** ROM `BCKXS1` (:7617+), 352 bytes, same origin. */
export const BCK_X_TABLE: readonly number[] = Object.freeze([
  17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
  17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
  17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
  17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
  17, 17, 17, 17, 16, 144, 144, 144, 144, 144, 144, 144, 144, 144, 144, 144,
  144, 144, 144, 144, 144, 144, 144, 144, 144, 144, 144, 144, 144, 144, 144, 144,
  144, 144, 128, 128, 128, 132, 132, 132, 132, 132, 132, 132, 132, 132, 132, 132,
  132, 132, 132, 132, 132, 132, 132, 132, 132, 196, 196, 196, 196, 196, 196, 196,
  196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196,
  196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196,
  196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196,
  196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196,
  196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 132, 132, 132, 132, 128, 128,
  128, 128, 128, 128, 128, 128, 128, 128, 128, 136, 136, 136, 136, 136, 136, 136,
  136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136,
  136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136,
  136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 138, 138, 138, 170, 170,
  42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42,
  42, 42, 42, 42, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
  34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
  34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
  34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
])

/**
 * The wave-1 landing mask for a pixel X — the ROM table with the wave init's
 * `ORA #$20` applied (`LNDXUP`, :987-989, *"FOR NOW, CLIFF 5 LANDS AT ALL
 * POINTS"*). Omitting that OR makes the bottom island unlandable outside its own
 * X span, which shows up as entities falling through the world.
 *
 * Outside the table's range there is no ground: the ROM's RAM buffer simply does
 * not extend there, and an entity that far off-screen has already wrapped.
 */
export function landMaskAtX(x: number): number {
  if (!Number.isInteger(x)) throw new TypeError(`landMaskAtX expects a whole pixel, got ${x}`)
  const i = x + X_TABLE_ORIGIN
  if (i < 0 || i >= LND_X_TABLE.length) return 0
  return LND_X_TABLE[i] | 0x20
}

/**
 * `LNDXTB[x] & LNDYTB[y]` (`CKGND`, :6705-6706) — the (x,y) → mask step jt1-4
 * defined a dispatch for but could not supply the input to.
 */
export function groundMaskAt(x: number, y: number): number {
  if (!Number.isInteger(y)) throw new TypeError(`groundMaskAt expects a whole scanline, got ${y}`)
  if (y < 0 || y >= LND_Y_TABLE.length) return 0
  return landMaskAtX(x) & LND_Y_TABLE[y]
}

// ─── Flight ─────────────────────────────────────────────────────────────────

const assertInt = (v: number, what: string): void => {
  if (!Number.isInteger(v)) throw new TypeError(`${what} must be a whole number, got ${v}`)
}

/** Sign-extend an 8-bit value — the 6809's `SEX` (:7290). */
const sex8 = (v: number): number => ((v & 0xff) << 24) >> 24

/** Exact 16-bit two's-complement wrap, so long trajectories match the ROM. */
const int16 = (v: number): number => ((v & 0xffff) << 16) >> 16

/**
 * Apply one flap edge (`ADDFLP`, :6429-6448). A no-op unless `input.flap` is
 * set — the edge is the shell's to detect.
 *
 * VERTICAL: `LDB PTIMUP / LDA #256*96/255 / MUL / TFR A,B / CLRA / SUBD #96`
 * gives ΔVY = ((timeUp × 96) >> 8) − 96, which is ADDED to the existing
 * velocity. A long climb yields a WEAKER impulse — hovering costs you lift, and
 * that decay is the mechanic the whole game rests on.
 *
 * HORIZONTAL: the joystick contributes ±2 to the index, and the result is
 * REJECTED, not clamped. `BGT ADXMX2` / `BLT ADXMX2` return WITHOUT storing, so
 * an over-range result leaves the index completely unchanged — a player at +8
 * who flaps right STAYS at +8, and the top rung is reachable only from exactly
 * one rung below. A saturating implementation looks similar and is wrong.
 * (The ROM's own comments on those two branches are inverted. Trust the branches.)
 *
 * The rejection is HORIZONTAL ONLY — a rejected flap still lifts.
 */
export function flap(state: EntityState, input: PlayerInput): EntityState {
  if (!input.flap) return state
  assertInt(state.timeUp, 'timeUp')
  assertInt(state.velY, 'velY')

  const impulse = ((state.timeUp * 96) >> 8) - 96
  const candidate = state.velXIndex + input.dir * 2
  const accepted =
    candidate >= 0 ? candidate <= MAX_VEL_X_INDEX : candidate >= -MAX_VEL_X_INDEX

  return {
    ...state,
    velY: int16(state.velY + impulse),
    velXIndex: accepted ? candidate : state.velXIndex,
  }
}

/**
 * Advance one frame of flight (`ADDGRA`/`ADDGRX`, :6489-6518).
 *
 * Gravity is added to VY, then VY is added to the 8.8 Y position. Horizontally
 * the FLYX word's LOW byte accumulates into `velXFrac` and only the CARRY plus
 * the sign-extended HIGH byte reach `posX` — which is what makes the shallow
 * rungs move a pixel every few frames rather than every frame.
 *
 * There is NO air drag and NO terminal velocity. Both are cited negative claims:
 * the FLYX index is STATE, not a decaying velocity, and gravity accumulates
 * without a cap until the floor or ceiling intervenes.
 */
export function stepFlight(state: EntityState, input: PlayerInput): EntityState {
  assertInt(state.posX, 'posX')
  assertInt(state.posY, 'posY')
  assertInt(state.velY, 'velY')
  assertInt(state.velXFrac, 'velXFrac')

  const gravity = input.flapHeld ? GRAVITY_WINGS_DOWN : GRAVITY_WINGS_UP
  const velY = int16(state.velY + gravity)
  const posY = state.posY + velY

  const rung = FLYX[state.velXIndex / 2 + 4]
  if (rung === undefined) throw new RangeError(`velXIndex ${state.velXIndex} is off the ladder`)
  const sum = state.velXFrac + (rung & 0xff)
  const velXFrac = sum & 0xff
  const whole = sex8(((rung >> 8) & 0xff) + (sum >> 8))

  return { ...state, posX: state.posX + whole, posY, velY, velXFrac }
}

/**
 * `AIRTIM` (:6476-6478): `INC / BNE / DEC` — saturate at 255, never wrap.
 * Wrapping would hand a fully-spent flapper a brand-new full-strength impulse.
 */
export function tickTimeUp(timeUp: number): number {
  assertInt(timeUp, 'timeUp')
  return timeUp >= 255 ? 255 : timeUp + 1
}

// ─── Ground ─────────────────────────────────────────────────────────────────

/**
 * One frame of ground movement: the STATE row's transition for the joystick
 * direction, plus the X delta.
 *
 * LIMITATION, stated rather than hidden: the ROM selects its per-frame delta
 * from `ORRUN` indexed by `PFRAME` (:7191-7196), the run-animation phase.
 * `EntityState` carries no such field, so the full 4→3→2→1→4 cycle cannot be
 * represented here; a skid uses SKID_DELTA and everything else uses the run
 * cycle's entry delta. Recorded as a Delivery Finding — the animation phase
 * belongs in the entity state before ground movement can be exact.
 */
export function stepGround(state: EntityState, input: PlayerInput, facing?: -1 | 1): EntityState {
  const current = state.groundState === null ? null : GROUND_STATES[state.groundState]
  if (!current) return state
  // The ROM's transitions are FACING-relative (`PLYRLP`, JOUSTRV4.SRC:5968-5983):
  // it negates the joystick when PFACE is left-facing, so `onPlus` means "with
  // your facing" and `onMinus` means "against it" (the reversal / skid path,
  // onMinus → a SKIDR state → PLANTZ 2). `EntityState` carries no facing field —
  // it is generated — so the caller threads PFACE in (jt2-9): with `facing`
  // supplied, a reversal (dir against facing) enters onMinus and the skid chain
  // becomes reachable from input; without it (legacy 2-arg callers), a non-zero
  // direction is read as forward, exactly as before.
  const nextId =
    input.dir === 0
      ? current.onZero
      : facing === undefined
        ? current.onPlus
        : input.dir === facing
          ? current.onPlus
          : current.onMinus
  const next = GROUND_STATES[nextId]
  if (!next) throw new RangeError(`${current.id} names an unknown state ${nextId}`)

  // RUNR (:7191-7196): LDB PFRAME / BLE RUNRST / DECB / BGT RUNFRM / LDB #4.
  // A phase at or below zero is "starting to run" and enters at 1; otherwise
  // decrement, wrapping past zero back to 4. So the cycle is 4,3,2,1,4,...
  const phase = state.animPhase ?? 0
  const nextPhase = phase <= 0 ? 1 : phase - 1 > 0 ? phase - 1 : 4

  // ORRUN (:7185-7189) is indexed BY the phase: index 1 -> 3px, 2 -> 2px,
  // 3 -> 1px, 4 -> 2px. One full cycle is 3+2+1+2 = 8px per 4 frames, so forty
  // held frames is exactly ten cycles = eighty pixels. A constant per-frame
  // delta would travel a plausible distance while erasing the ROM's gait.
  const running = next.call === 'RUNR' || next.call === 'RUNSR'
  const skidding = next.call === 'SKIDR'
  const delta = skidding ? SKID_DELTA : running ? ORRUN_DELTAS[nextPhase] : 0

  return {
    ...state,
    groundState: next.id,
    animPhase: running ? nextPhase : 0,
    posX: state.posX + delta * input.dir,
    plantZ: skidding ? SKID_PLANT_Z : state.plantZ,
  }
}

/**
 * Flap-initiated takeoff (`STFLY`, :6123-6128): VY = −$0080, then
 * `DEC PPOSY+1,U` lifts one WHOLE pixel to clear the landing band, and both
 * sub-pixel fractions are cleared. Without the lift the entity re-lands on the
 * same frame it took off.
 */
export function takeOff(state: EntityState): EntityState {
  return {
    ...state,
    velY: TAKEOFF_VEL_Y,
    posY: ((state.posY >> 8) - 1) << 8,
    velXFrac: 0,
    airborne: true,
    groundState: null,
  }
}

/**
 * Walking off an edge (`STFALL`, :6139-6151): VY = 0 and the fractions cleared,
 * but NO lift. The entity simply stops being supported — which is what makes
 * stepping off a ledge feel different from jumping.
 */
export function walkOff(state: EntityState): EntityState {
  return {
    ...state,
    // Without this a saturated glide walks off with timeUp 255 and the next
    // flap lifts by -1 instead of -96. Also from the jt1-5 review reversal.
    timeUp: 0,
    velY: 0,
    posY: (state.posY >> 8) << 8,
    velXFrac: 0,
    airborne: true,
    groundState: null,
  }
}

/**
 * Landing (`FRCONV`, :6253-6257): the incoming horizontal speed selects the
 * ground state — standing at rest, through four running speeds. The Y snap
 * itself is the arena's (`LNDBn`), so this takes the platform's snapY as given.
 *
 * `PTIMUP` resets here and ONLY here: it never resets in flight, so a long
 * glide's spent impulse is only restored by touching down.
 */
export function land(state: EntityState, platform: { snapY: number }): EntityState {
  const speed = Math.min(Math.abs(state.velXIndex) / 2, FRCONV.length - 1)
  return {
    ...state,
    posY: platform.snapY << 8,
    velY: 0,
    velXFrac: 0,
    // STLDIR writes LDA #1 — the ROM's MINIMUM DOWN TIME, not zero. Restored
    // from the jt1-5 review reversal (0ff5591) after the generator, which
    // predates that hotfix, regenerated over it in jt1-6.
    timeUp: 1,
    airborne: false,
    animPhase: 0,
    groundState: FRCONV[speed],
  }
}

// ─── jt5-3: the two-edge wing cue ───────────────────────────────────────────
//
// FLAPLP/FLIPLP (:6163-6210) is a two-loop coroutine, not a per-frame edge
// test: an airborne bird sounds wing-DOWN on the PRESS (GOFLAP -> FLAST2,
// :6212-6218) and wing-UP on the RELEASE (GOFLIP, :6182-6184); holding
// re-enters its loop BELOW the cue (FLAPS2 :6170 / FLIPS2 :6197) and stays
// silent. A flap TAKE-OFF (STFLY, :6123-6135) jumps straight onto the
// wing-down cue; walking off a ledge (STFALL, :6139-6157) and every other
// grounded transition (PLYRLP, :5948-6024) has no wing sound at all — and
// since `input.flap` (the shell's rising edge) is the ONLY thing that ever
// calls `takeOff()` below, checking it is checking exactly the STFLY/STFALL
// fork.
//
// This function is itself pure and carries no memory of its own:
// `wasAirborne` and `prevFlapHeld` are the CALLER's record of the previous
// frame (a player) or the previous wake (an enemy) — see frame.ts's
// `runBehaviour` and enemy.ts's `stepEnemyDetailed`, which is also where the
// value returned here becomes a `GameEvent`.
export type WingEdge = 'down' | 'up' | null

export function wingEdge(wasAirborne: boolean, prevFlapHeld: boolean, input: PlayerInput): WingEdge {
  if (!wasAirborne) return input.flap ? 'down' : null
  if (input.flapHeld && !prevFlapHeld) return 'down'
  if (!input.flapHeld && prevFlapHeld) return 'up'
  return null
}
