// GENERATED by scripts/gen-registry.mjs — do not edit by hand.
// Run `npm run gen:registry` after changing any plugins/*/plugin.ts.
//
// This file replaced lobby/src/core/registry.ts, which was maintained by hand and
// silently drifted from what was actually deployed. Every entry below was validated
// by src/host/contract.ts's validateMeta at generation time, and src/host/registry.test.ts
// re-validates both the manifests and this file on every test run.
import type { GameMeta } from './contract'

/** Every game on the cabinet, in curated tile order — the `order` field, not the
 *  directory order the filesystem happens to hand back. */
export const GAMES: readonly GameMeta[] = [
  {
    id: 'tempest',
    title: 'TEMPEST',
    year: 1981,
    color: '#00eaff',
    controls: ['ROTATE — Wheel / ←→', 'FIRE — Click / Space'],
    order: 1,
    listed: true,
    showcase: true,
    version: '1.0.30',
  },
  {
    id: 'star-wars',
    title: 'STAR WARS',
    year: 1983,
    color: '#ffe81f',
    controls: ['AIM — Mouse', 'FIRE — Click / Space'],
    order: 2,
    listed: true,
    showcase: false,
    version: '0.0.35',
  },
  {
    id: 'asteroids',
    title: 'ASTEROIDS',
    year: 1979,
    color: '#ff6a00',
    controls: ['ROTATE/THRUST — ←→↑ / WASD', 'FIRE — Space / K'],
    order: 3,
    listed: true,
    showcase: false,
    version: '1.0.15',
  },
  {
    id: 'battlezone',
    title: 'BATTLEZONE',
    year: 1980,
    color: '#00ff41',
    controls: ['DRIVE — Arrows / E D I K', 'FIRE — Space / F'],
    order: 4,
    listed: true,
    showcase: false,
    version: '1.0.4',
  },
  {
    id: 'centipede',
    title: 'CENTIPEDE',
    year: 1981,
    color: '#2aa358',
    controls: ['Mouse'],
    order: 5,
    listed: true,
    showcase: true,
    version: '0.0.10',
  },
  {
    id: 'joust',
    title: 'JOUST',
    year: 1982,
    color: '#f0a828',
    controls: ['MOVE — ←→ / A D', 'FLAP — Space / Shift'],
    order: 6,
    listed: true,
    showcase: false,
    version: '0.0.10',
  },
  {
    id: 'red-baron',
    title: 'RED BARON',
    year: 1980,
    color: '#d43b3b',
    controls: ['FLY — Mouse / Arrows', 'FIRE — Click / Space'],
    order: 7,
    listed: false,
    showcase: false,
    version: '0.0.24',
  },
]

/** The games the lobby lists — `listed: false` opts a game out deliberately. */
export const LISTED_GAMES: readonly GameMeta[] = GAMES.filter((g) => g.listed)

/** The path a game is served at on the single origin. Replaces the old
 *  hand-maintained absolute `launchUrl`, which could drift from reality. */
export function gamePath(id: string): string {
  return `/${id}/`
}

/** Look up a game by id; `undefined` when no game matches. */
export function getGame(id: string): GameMeta | undefined {
  return GAMES.find((g) => g.id === id)
}
