// src/core/charset-data.ts
//
// @generated by scripts/transcribe-charset.mjs from
// reference/original-source/defender/MESS0.SRC — DO NOT EDIT BY HAND.
// Re-run `node scripts/transcribe-charset.mjs` to regenerate.
//
// The Defender MESS0 character set (defender/MESS0.SRC:441-640): one record per
// distinct CHRTBL glyph. `bytes` is the effective WW×HH cell (big-endian, sliced
// from the source block; SPACE aliases the oversized BLANK). Every byte is
// re-derived and refused-on-mismatch by tests/charset-gate.test.ts. PURE data —
// no colour, no clock, no import; the shell decodes an index to RGBA, not this.

/** One transcribed charset glyph: raster ROM cell pixels as 4-bit palette indices. */
export interface GlyphData {
  readonly name: string
  /** The ASCII character this glyph renders, or null (the alphabet blank). */
  readonly char: string | null
  readonly width: number
  readonly height: number
  /** Encoding discriminant — 'raster' cells are the only kind blitGlyph may draw. */
  readonly encoding: 'raster'
  /** The effective cell: exactly width×height bytes, big-endian from the source. */
  readonly bytes: readonly number[]
  /** Provenance: the MESS0.SRC CHRTBL label this cell was transcribed from. */
  readonly source: { readonly file: string; readonly label: string }
}

export const CHARSET: readonly GlyphData[] = [
  { name: "SPACE", char: " ", width: 1, height: 8, encoding: 'raster', bytes: [0, 0, 0, 0, 0, 0, 0, 0], source: { file: "MESS0.SRC", label: "SPACE" } },
  { name: "EXCLPT", char: "!", width: 1, height: 8, encoding: 'raster', bytes: [1, 1, 1, 1, 1, 0, 1, 0], source: { file: "MESS0.SRC", label: "EXCLPT" } },
  { name: "COMMA", char: ",", width: 1, height: 8, encoding: 'raster', bytes: [0, 0, 0, 0, 0, 1, 1, 16], source: { file: "MESS0.SRC", label: "COMMA" } },
  { name: "QUESMK", char: "?", width: 3, height: 8, encoding: 'raster', bytes: [1, 1, 0, 0, 0, 0, 0, 0, 17, 0, 0, 1, 1, 0, 1, 0, 17, 17, 17, 16, 0, 0, 0, 0], source: { file: "MESS0.SRC", label: "QUESMK" } },
  { name: "PERIOD", char: ".", width: 1, height: 8, encoding: 'raster', bytes: [0, 0, 0, 0, 0, 0, 1, 0], source: { file: "MESS0.SRC", label: "PERIOD" } },
  { name: "NUMBR0", char: "0", width: 3, height: 8, encoding: 'raster', bytes: [1, 1, 1, 1, 1, 1, 1, 0, 17, 0, 0, 0, 0, 0, 17, 0, 17, 17, 17, 17, 17, 17, 17, 0], source: { file: "MESS0.SRC", label: "NUMBR0" } },
  { name: "NUMBR1", char: "1", width: 3, height: 8, encoding: 'raster', bytes: [0, 0, 1, 0, 0, 0, 0, 0, 1, 17, 16, 0, 0, 0, 0, 0, 17, 17, 17, 17, 17, 17, 17, 0], source: { file: "MESS0.SRC", label: "NUMBR1" } },
  { name: "NUMBR2", char: "2", width: 3, height: 8, encoding: 'raster', bytes: [1, 1, 0, 0, 0, 1, 1, 0, 17, 0, 0, 1, 16, 0, 17, 0, 17, 17, 17, 16, 0, 0, 17, 0], source: { file: "MESS0.SRC", label: "NUMBR2" } },
  { name: "NUMBR3", char: "3", width: 3, height: 8, encoding: 'raster', bytes: [1, 0, 0, 0, 0, 0, 1, 0, 17, 0, 0, 17, 0, 0, 17, 0, 17, 17, 17, 17, 17, 17, 17, 0], source: { file: "MESS0.SRC", label: "NUMBR3" } },
  { name: "NUMBR4", char: "4", width: 3, height: 8, encoding: 'raster', bytes: [0, 0, 1, 1, 0, 0, 0, 0, 1, 16, 0, 17, 0, 0, 0, 0, 17, 17, 17, 17, 17, 17, 17, 0], source: { file: "MESS0.SRC", label: "NUMBR4" } },
  { name: "NUMBR5", char: "5", width: 3, height: 8, encoding: 'raster', bytes: [1, 1, 1, 1, 0, 0, 1, 0, 17, 16, 16, 17, 0, 0, 17, 0, 17, 0, 0, 17, 1, 1, 17, 0], source: { file: "MESS0.SRC", label: "NUMBR5" } },
  { name: "NUMBR6", char: "6", width: 3, height: 8, encoding: 'raster', bytes: [1, 1, 1, 1, 1, 1, 1, 0, 17, 16, 16, 17, 16, 16, 17, 0, 17, 0, 0, 17, 1, 1, 17, 0], source: { file: "MESS0.SRC", label: "NUMBR6" } },
  { name: "NUMBR7", char: "7", width: 3, height: 8, encoding: 'raster', bytes: [1, 0, 0, 0, 0, 1, 1, 0, 17, 0, 0, 1, 17, 16, 16, 0, 17, 17, 17, 16, 0, 0, 0, 0], source: { file: "MESS0.SRC", label: "NUMBR7" } },
  { name: "NUMBR8", char: "8", width: 3, height: 8, encoding: 'raster', bytes: [1, 1, 1, 0, 1, 1, 1, 0, 17, 16, 16, 17, 16, 16, 17, 0, 17, 1, 1, 16, 1, 1, 17, 0], source: { file: "MESS0.SRC", label: "NUMBR8" } },
  { name: "NUMBR9", char: "9", width: 3, height: 8, encoding: 'raster', bytes: [1, 1, 1, 1, 0, 0, 1, 0, 17, 16, 16, 17, 0, 0, 17, 0, 17, 1, 1, 17, 1, 1, 17, 0], source: { file: "MESS0.SRC", label: "NUMBR9" } },
  { name: "COLON", char: ":", width: 1, height: 8, encoding: 'raster', bytes: [0, 0, 1, 0, 0, 1, 0, 0], source: { file: "MESS0.SRC", label: "COLON" } },
  { name: "BLANK", char: null, width: 3, height: 8, encoding: 'raster', bytes: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], source: { file: "MESS0.SRC", label: "BLANK" } },
  { name: "LETTRA", char: "A", width: 3, height: 8, encoding: 'raster', bytes: [1, 1, 1, 1, 1, 1, 1, 0, 17, 0, 0, 17, 0, 0, 0, 0, 17, 17, 17, 17, 17, 17, 17, 0], source: { file: "MESS0.SRC", label: "LETTRA" } },
  { name: "LETTRB", char: "B", width: 3, height: 8, encoding: 'raster', bytes: [1, 1, 1, 1, 1, 1, 1, 0, 17, 0, 0, 17, 0, 0, 17, 0, 17, 17, 17, 17, 17, 17, 17, 0], source: { file: "MESS0.SRC", label: "LETTRB" } },
  { name: "LETTRC", char: "C", width: 3, height: 8, encoding: 'raster', bytes: [1, 1, 1, 1, 1, 1, 1, 0, 17, 16, 16, 16, 16, 16, 17, 0, 17, 0, 0, 0, 0, 0, 17, 0], source: { file: "MESS0.SRC", label: "LETTRC" } },
  { name: "LETTRD", char: "D", width: 3, height: 8, encoding: 'raster', bytes: [1, 1, 1, 1, 1, 1, 1, 0, 17, 0, 0, 0, 0, 0, 17, 0, 16, 17, 17, 17, 17, 17, 16, 0], source: { file: "MESS0.SRC", label: "LETTRD" } },
  { name: "LETTRE", char: "E", width: 3, height: 8, encoding: 'raster', bytes: [1, 1, 1, 1, 1, 1, 1, 0, 17, 16, 16, 17, 16, 16, 17, 0, 17, 0, 0, 16, 0, 0, 17, 0], source: { file: "MESS0.SRC", label: "LETTRE" } },
  { name: "LETTRF", char: "F", width: 3, height: 8, encoding: 'raster', bytes: [1, 1, 1, 1, 1, 1, 1, 0, 17, 16, 16, 17, 16, 16, 16, 0, 17, 0, 0, 16, 0, 0, 0, 0], source: { file: "MESS0.SRC", label: "LETTRF" } },
  { name: "LETTRG", char: "G", width: 3, height: 8, encoding: 'raster', bytes: [1, 1, 1, 1, 1, 1, 1, 0, 17, 16, 16, 16, 16, 16, 17, 0, 17, 0, 0, 17, 1, 1, 17, 0], source: { file: "MESS0.SRC", label: "LETTRG" } },
  { name: "LETTRH", char: "H", width: 3, height: 8, encoding: 'raster', bytes: [1, 1, 1, 1, 1, 1, 1, 0, 16, 16, 16, 17, 16, 16, 16, 0, 1, 1, 1, 17, 1, 1, 1, 0], source: { file: "MESS0.SRC", label: "LETTRH" } },
  { name: "LETTRI", char: "I", width: 2, height: 8, encoding: 'raster', bytes: [1, 1, 1, 1, 1, 1, 1, 0, 16, 16, 16, 16, 16, 16, 16, 0], source: { file: "MESS0.SRC", label: "LETTRI" } },
  { name: "LETTRJ", char: "J", width: 3, height: 8, encoding: 'raster', bytes: [0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 17, 0, 17, 17, 17, 17, 17, 17, 17, 0], source: { file: "MESS0.SRC", label: "LETTRJ" } },
  { name: "LETTRK", char: "K", width: 3, height: 8, encoding: 'raster', bytes: [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 17, 1, 0, 0, 0, 1, 16, 0, 0, 0, 16, 1, 0], source: { file: "MESS0.SRC", label: "LETTRK" } },
  { name: "LETTRL", char: "L", width: 3, height: 8, encoding: 'raster', bytes: [1, 1, 1, 1, 1, 1, 1, 0, 16, 16, 16, 16, 16, 16, 17, 0, 0, 0, 0, 0, 0, 0, 17, 0], source: { file: "MESS0.SRC", label: "LETTRL" } },
  { name: "LETTRM", char: "M", width: 4, height: 8, encoding: 'raster', bytes: [1, 1, 1, 1, 1, 1, 1, 0, 17, 16, 16, 16, 16, 16, 16, 0, 17, 16, 16, 16, 0, 0, 0, 0, 17, 17, 17, 17, 17, 17, 17, 0], source: { file: "MESS0.SRC", label: "LETTRM" } },
  { name: "LETTRN", char: "N", width: 3, height: 8, encoding: 'raster', bytes: [1, 1, 1, 1, 1, 1, 1, 0, 17, 16, 16, 16, 16, 16, 16, 0, 17, 1, 1, 1, 1, 1, 1, 0], source: { file: "MESS0.SRC", label: "LETTRN" } },
  { name: "LETTRO", char: "O", width: 3, height: 8, encoding: 'raster', bytes: [1, 1, 1, 1, 1, 1, 1, 0, 17, 16, 16, 16, 16, 16, 17, 0, 17, 1, 1, 1, 1, 1, 17, 0], source: { file: "MESS0.SRC", label: "LETTRO" } },
  { name: "LETTRP", char: "P", width: 3, height: 8, encoding: 'raster', bytes: [1, 1, 1, 1, 1, 1, 1, 0, 17, 16, 16, 17, 16, 16, 16, 0, 17, 1, 1, 17, 0, 0, 0, 0], source: { file: "MESS0.SRC", label: "LETTRP" } },
  { name: "LETTRQ", char: "Q", width: 3, height: 8, encoding: 'raster', bytes: [1, 1, 1, 1, 1, 1, 1, 0, 17, 16, 16, 16, 16, 16, 17, 0, 17, 1, 1, 1, 1, 17, 17, 16], source: { file: "MESS0.SRC", label: "LETTRQ" } },
  { name: "LETTRR", char: "R", width: 3, height: 8, encoding: 'raster', bytes: [1, 1, 1, 1, 1, 1, 1, 0, 17, 16, 16, 17, 16, 16, 16, 0, 17, 1, 1, 17, 16, 1, 1, 0], source: { file: "MESS0.SRC", label: "LETTRR" } },
  { name: "LETTRS", char: "S", width: 3, height: 8, encoding: 'raster', bytes: [1, 1, 1, 1, 0, 0, 1, 0, 17, 16, 16, 17, 0, 0, 17, 0, 17, 0, 0, 17, 17, 17, 17, 0], source: { file: "MESS0.SRC", label: "LETTRS" } },
  { name: "LETTRT", char: "T", width: 3, height: 8, encoding: 'raster', bytes: [17, 0, 0, 0, 0, 0, 0, 0, 17, 17, 17, 17, 17, 17, 17, 0, 17, 0, 0, 0, 0, 0, 0, 0], source: { file: "MESS0.SRC", label: "LETTRT" } },
  { name: "LETTRU", char: "U", width: 3, height: 8, encoding: 'raster', bytes: [1, 1, 1, 1, 1, 1, 1, 0, 16, 16, 16, 16, 16, 16, 17, 0, 1, 1, 1, 1, 1, 1, 17, 0], source: { file: "MESS0.SRC", label: "LETTRU" } },
  { name: "LETTRV", char: "V", width: 3, height: 8, encoding: 'raster', bytes: [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 16, 1, 0, 1, 1, 1, 1, 1, 16, 0, 0], source: { file: "MESS0.SRC", label: "LETTRV" } },
  { name: "LETTRW", char: "W", width: 4, height: 8, encoding: 'raster', bytes: [1, 1, 1, 1, 1, 1, 0, 0, 16, 16, 16, 16, 16, 16, 1, 0, 16, 16, 16, 16, 16, 16, 1, 0, 16, 16, 16, 16, 16, 16, 0, 0], source: { file: "MESS0.SRC", label: "LETTRW" } },
  { name: "LETTRX", char: "X", width: 3, height: 8, encoding: 'raster', bytes: [1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 16, 1, 16, 0, 0, 0, 1, 1, 16, 0, 16, 1, 1, 0], source: { file: "MESS0.SRC", label: "LETTRX" } },
  { name: "LETTRY", char: "Y", width: 3, height: 8, encoding: 'raster', bytes: [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 16, 1, 1, 1, 1, 0, 1, 1, 16, 0, 0, 0, 0, 0], source: { file: "MESS0.SRC", label: "LETTRY" } },
  { name: "LETTRZ", char: "Z", width: 3, height: 8, encoding: 'raster', bytes: [1, 0, 0, 0, 1, 1, 1, 0, 17, 0, 1, 16, 0, 0, 17, 0, 17, 16, 0, 0, 0, 0, 17, 0], source: { file: "MESS0.SRC", label: "LETTRZ" } },
]
