// src/core/objects-data.ts
//
// @generated by scripts/transcribe-objects.mjs from
// reference/original-source/defender/DEFB6.SRC (+ SAMEXAP7.SRC) — DO NOT EDIT BY HAND.
// Re-run `node scripts/transcribe-objects.mjs` to regenerate.
//
// Defender's object graphics (defender/DEFB6.SRC): one 'raster' record per picture
// descriptor `LABEL FCB W,H` — `bytes` is the first field's W×H cell (big-endian,
// FDB words or FCB bytes as the ROM stores them). SAMEXAP7 (defender/SAMEXAP7.SRC) is
// the explosion/appear CODE, not a pixel table, so it lands as the single 'stream'
// block the render seam REFUSES to raster (streams-are-not-rasters). Every byte is
// re-derived and refused-on-mismatch by tests/objects-gate.test.ts. PURE data — no
// colour, no clock, no import; a byte packs two 4-bit palette indices.

/** Block encoding discriminant — 'raster' cells are the only kind blitObject may draw. */
export type ObjectEncoding = 'raster' | 'stream'

/** One transcribed object image: raster ROM cell pixels as 4-bit palette indices,
 *  or a non-raster block (empty `bytes`) that the render seam refuses to raster. */
export interface ObjectImageData {
  readonly name: string
  /** Bytes per row (a byte is two horizontal pixels); 0 for a non-raster block. */
  readonly width: number
  /** Rows; 0 for a non-raster block. */
  readonly height: number
  readonly encoding: ObjectEncoding
  /** A raster's effective cell: exactly width×height bytes; empty for a non-raster. */
  readonly bytes: readonly number[]
  /** Provenance: the vendored file, the label transcribed, and its 1-based line. */
  readonly source: { readonly file: string; readonly label: string; readonly line: number }
}

export const OBJECTS: readonly ObjectImageData[] = [
  { name: "SCZP1", width: 5, height: 8, encoding: 'raster', bytes: [0, 0, 3, 3, 0, 0, 3, 48, 12, 60, 12, 8, 56, 48, 0, 0, 192, 192, 200, 120, 120, 112, 112, 112, 0, 48, 3, 3, 48, 48, 3, 0, 0, 0, 0, 0, 0, 0, 0, 48], source: { file: "DEFB6.SRC", label: "SCZP1", line: 1896 } },
  { name: "ASXP1", width: 4, height: 8, encoding: 'raster', bytes: [0, 0, 13, 108, 108, 13, 0, 0, 6, 230, 200, 131, 130, 200, 236, 6, 96, 109, 140, 40, 40, 140, 109, 96, 0, 0, 224, 198, 198, 224, 0, 0], source: { file: "DEFB6.SRC", label: "ASXP1", line: 1899 } },
  { name: "SWXP1", width: 4, height: 8, encoding: 'raster', bytes: [0, 0, 2, 34, 36, 2, 0, 0, 2, 34, 68, 68, 36, 66, 34, 0, 32, 34, 68, 68, 36, 66, 34, 0, 0, 0, 32, 34, 34, 32, 0, 0], source: { file: "DEFB6.SRC", label: "SWXP1", line: 1902 } },
  { name: "NULOB", width: 1, height: 1, encoding: 'raster', bytes: [0], source: { file: "DEFB6.SRC", label: "NULOB", line: 1905 } },
  { name: "PRBP1", width: 4, height: 8, encoding: 'raster', bytes: [0, 14, 0, 216, 0, 14, 0, 0, 15, 8, 140, 200, 140, 8, 15, 0, 0, 14, 128, 200, 128, 14, 0, 0, 0, 0, 0, 208, 0, 0, 0, 0], source: { file: "DEFB6.SRC", label: "PRBP1", line: 1909 } },
  { name: "ASTP1", width: 2, height: 8, encoding: 'raster', bytes: [51, 67, 67, 135, 135, 7, 7, 7, 0, 0, 128, 128, 128, 0, 0, 0], source: { file: "DEFB6.SRC", label: "ASTP1", line: 1913 } },
  { name: "ASTP2", width: 2, height: 8, encoding: 'raster', bytes: [51, 67, 67, 135, 135, 119, 119, 119, 0, 0, 128, 128, 128, 0, 0, 0], source: { file: "DEFB6.SRC", label: "ASTP2", line: 1915 } },
  { name: "ASTP3", width: 2, height: 8, encoding: 'raster', bytes: [3, 3, 131, 135, 135, 7, 7, 7, 48, 64, 64, 128, 128, 0, 0, 0], source: { file: "DEFB6.SRC", label: "ASTP3", line: 1918 } },
  { name: "ASTP4", width: 2, height: 8, encoding: 'raster', bytes: [3, 3, 131, 135, 135, 7, 7, 7, 48, 64, 64, 128, 128, 112, 112, 112], source: { file: "DEFB6.SRC", label: "ASTP4", line: 1920 } },
  { name: "TIEP1", width: 4, height: 8, encoding: 'raster', bytes: [8, 8, 221, 222, 222, 222, 221, 0, 136, 136, 221, 238, 254, 238, 221, 0, 136, 136, 216, 216, 216, 208, 208, 0, 0, 0, 0, 0, 0, 0, 0, 0], source: { file: "DEFB6.SRC", label: "TIEP1", line: 1923 } },
  { name: "TIEP2", width: 4, height: 8, encoding: 'raster', bytes: [0, 8, 221, 222, 222, 222, 221, 0, 0, 136, 221, 238, 254, 238, 221, 0, 0, 136, 216, 216, 216, 216, 208, 0, 0, 0, 0, 0, 0, 0, 0, 0], source: { file: "DEFB6.SRC", label: "TIEP2", line: 1925 } },
  { name: "TIEP3", width: 4, height: 8, encoding: 'raster', bytes: [0, 0, 221, 222, 222, 222, 221, 0, 0, 0, 221, 238, 254, 238, 221, 0, 0, 0, 216, 216, 216, 216, 216, 0, 0, 0, 0, 0, 0, 0, 0, 0], source: { file: "DEFB6.SRC", label: "TIEP3", line: 1927 } },
  { name: "TIEP4", width: 4, height: 8, encoding: 'raster', bytes: [0, 0, 221, 222, 222, 222, 221, 0, 0, 0, 221, 238, 254, 238, 221, 136, 0, 0, 208, 216, 216, 216, 216, 136, 0, 0, 0, 0, 0, 0, 0, 0], source: { file: "DEFB6.SRC", label: "TIEP4", line: 1929 } },
  { name: "BXPIC", width: 4, height: 8, encoding: 'raster', bytes: [0, 12, 204, 204, 204, 204, 12, 0, 204, 204, 204, 204, 204, 204, 204, 204, 204, 204, 204, 204, 204, 204, 204, 204, 0, 192, 204, 204, 204, 204, 192, 0], source: { file: "DEFB6.SRC", label: "BXPIC", line: 1932 } },
  { name: "BMBP1", width: 2, height: 3, encoding: 'raster', bytes: [160, 10, 160, 160, 0, 160], source: { file: "DEFB6.SRC", label: "BMBP1", line: 1935 } },
  { name: "BMBP2", width: 2, height: 3, encoding: 'raster', bytes: [10, 170, 10, 0, 160, 0], source: { file: "DEFB6.SRC", label: "BMBP2", line: 1937 } },
  { name: "LASP1", width: 8, height: 1, encoding: 'raster', bytes: [255, 255, 255, 255, 255, 255, 255, 255], source: { file: "DEFB6.SRC", label: "LASP1", line: 1940 } },
  { name: "SWPIC1", width: 3, height: 4, encoding: 'raster', bytes: [0, 2, 35, 2, 32, 34, 35, 34, 0, 0, 32, 0], source: { file: "DEFB6.SRC", label: "SWPIC1", line: 1944 } },
  { name: "LNDP1", width: 5, height: 8, encoding: 'raster', bytes: [0, 0, 3, 3, 0, 0, 3, 48, 4, 52, 48, 48, 52, 48, 0, 0, 68, 68, 51, 51, 52, 48, 48, 48, 0, 48, 3, 3, 48, 48, 3, 0, 0, 0, 0, 0, 0, 0, 0, 48], source: { file: "DEFB6.SRC", label: "LNDP1", line: 1947 } },
  { name: "LNDP2", width: 5, height: 8, encoding: 'raster', bytes: [0, 0, 3, 3, 0, 0, 3, 48, 4, 52, 3, 3, 52, 48, 0, 0, 68, 68, 48, 48, 52, 48, 48, 48, 0, 48, 51, 51, 48, 48, 3, 0, 0, 0, 0, 0, 0, 0, 0, 48], source: { file: "DEFB6.SRC", label: "LNDP2", line: 1949 } },
  { name: "LNDP3", width: 5, height: 8, encoding: 'raster', bytes: [0, 0, 3, 3, 0, 0, 3, 48, 0, 51, 51, 51, 51, 48, 0, 0, 0, 51, 3, 3, 51, 48, 48, 48, 0, 48, 51, 51, 48, 48, 3, 0, 0, 0, 0, 0, 0, 0, 0, 48], source: { file: "DEFB6.SRC", label: "LNDP3", line: 1951 } },
  { name: "UFOP1", width: 6, height: 4, encoding: 'raster', bytes: [0, 3, 52, 3, 51, 112, 64, 51, 51, 7, 68, 51, 51, 0, 4, 51, 48, 115, 64, 51, 0, 0, 48, 0], source: { file: "DEFB6.SRC", label: "UFOP1", line: 1954 } },
  { name: "UFOP2", width: 6, height: 4, encoding: 'raster', bytes: [0, 3, 48, 3, 51, 0, 68, 51, 51, 112, 4, 51, 51, 7, 64, 51, 48, 3, 68, 51, 0, 0, 48, 0], source: { file: "DEFB6.SRC", label: "UFOP2", line: 1956 } },
  { name: "UFOP3", width: 6, height: 4, encoding: 'raster', bytes: [0, 3, 52, 3, 51, 7, 4, 51, 51, 0, 64, 51, 51, 112, 68, 51, 48, 3, 4, 51, 0, 0, 48, 0], source: { file: "DEFB6.SRC", label: "UFOP3", line: 1958 } },
  { name: "PLAPIC", width: 8, height: 6, encoding: 'raster', bytes: [0, 6, 38, 6, 38, 0, 102, 102, 102, 136, 136, 136, 0, 96, 102, 102, 136, 134, 0, 0, 0, 102, 102, 147, 0, 0, 0, 109, 102, 0, 0, 0, 0, 239, 102, 0, 0, 0, 0, 0, 105, 0, 0, 0, 0, 0, 48, 0], source: { file: "DEFB6.SRC", label: "PLAPIC", line: 1961 } },
  { name: "PLBPIC", width: 8, height: 6, encoding: 'raster', bytes: [0, 0, 0, 0, 57, 0, 0, 0, 0, 15, 102, 0, 0, 0, 0, 237, 102, 0, 0, 0, 0, 102, 102, 3, 0, 0, 6, 102, 104, 150, 6, 102, 102, 104, 136, 136, 96, 102, 102, 131, 134, 128, 0, 0, 48, 0, 48, 0], source: { file: "DEFB6.SRC", label: "PLBPIC", line: 1963 } },
  { name: "PLAMIN", width: 5, height: 4, encoding: 'raster', bytes: [6, 38, 104, 40, 96, 102, 102, 134, 0, 0, 102, 102, 0, 0, 237, 102, 0, 0, 0, 99], source: { file: "DEFB6.SRC", label: "PLAMIN", line: 1966 } },
  { name: "SBPIC", width: 3, height: 3, encoding: 'raster', bytes: [144, 9, 144, 153, 153, 153, 144, 204, 144], source: { file: "DEFB6.SRC", label: "SBPIC", line: 1969 } },
  { name: "C25P1", width: 6, height: 6, encoding: 'raster', bytes: [17, 0, 17, 16, 17, 0, 16, 16, 16, 0, 16, 0, 17, 16, 17, 0, 17, 0, 16, 0, 16, 16, 16, 0, 17, 16, 16, 16, 17, 0, 16, 16, 16, 16, 16, 0], source: { file: "DEFB6.SRC", label: "C25P1", line: 1972 } },
  { name: "C5P1", width: 6, height: 6, encoding: 'raster', bytes: [255, 240, 255, 0, 255, 0, 240, 0, 240, 240, 240, 0, 238, 224, 224, 224, 238, 0, 224, 224, 224, 224, 224, 0, 221, 208, 208, 208, 221, 0, 208, 208, 208, 208, 208, 0], source: { file: "DEFB6.SRC", label: "C5P1", line: 1975 } },
  { name: "TEREX", width: 8, height: 6, encoding: 'raster', bytes: [28, 13, 127, 231, 112, 0, 15, 113, 113, 7, 220, 119, 124, 13, 113, 199, 119, 222, 7, 113, 23, 23, 222, 247, 113, 23, 113, 124, 222, 240, 7, 119, 199, 113, 23, 112, 112, 124, 215, 119, 119, 112, 1, 205, 255, 215, 112, 240], source: { file: "DEFB6.SRC", label: "TEREX", line: 1978 } },
  { name: "SAMEXAP7", width: 0, height: 0, encoding: 'stream', bytes: [], source: { file: "SAMEXAP7.SRC", label: "APST", line: 23 } },
]
