// src/core/terrain-data.ts
//
// @generated by scripts/transcribe-terrain.mjs from
// reference/original-source/defender/BLK71.SRC — DO NOT EDIT BY HAND.
// Re-run `node scripts/transcribe-terrain.mjs` to regenerate.
//
// Defender's terrain data (defender/BLK71.SRC, banked block 7). The block is mostly
// terrain-generation CODE plus PLAYER EXPLOSION data; only two labels are terrain
// DATA: TDATA (the 256-byte 'bitstream' height profile, TLEN=$100) and MTERR (the
// 384-byte scanner 'stream'). NEITHER is a 'raster' — terrain is a byte/bit stream,
// never a nibble grid (streams-are-not-rasters). Every byte is re-derived and
// refused-on-mismatch by tests/terrain-gate.test.ts. PURE data — no colour, no clock,
// no import.

/** Block encoding discriminant. Neither kind is a nibble raster: 'bitstream' is the
 *  TDATA height profile decodeScrollSurface walks; 'stream' is the MTERR scanner data. */
export type TerrainEncoding = 'bitstream' | 'stream'

/** One transcribed BLK71 terrain block: a flat byte run from the vendored source. */
export interface TerrainBlockData {
  readonly name: string
  readonly encoding: TerrainEncoding
  /** The transcribed bytes, big-endian from source. */
  readonly bytes: readonly number[]
  /** Provenance: the vendored file, the label transcribed, and its 1-based line. */
  readonly source: { readonly file: string; readonly label: string; readonly line: number }
}

export const TERRAIN: readonly TerrainBlockData[] = [
  { name: "TDATA", encoding: 'bitstream', bytes: [42, 170, 170, 170, 170, 170, 171, 161, 213, 85, 85, 85, 85, 85, 170, 191, 255, 255, 255, 192, 0, 0, 0, 85, 85, 87, 255, 192, 1, 85, 85, 85, 85, 85, 85, 95, 224, 21, 85, 85, 87, 255, 240, 0, 21, 85, 95, 255, 255, 255, 255, 0, 0, 0, 0, 5, 85, 127, 255, 224, 0, 5, 85, 85, 85, 85, 252, 5, 85, 85, 80, 1, 255, 255, 255, 192, 0, 10, 170, 170, 170, 255, 0, 0, 255, 255, 255, 255, 240, 0, 0, 31, 224, 0, 85, 85, 85, 64, 170, 170, 170, 170, 170, 170, 181, 87, 170, 170, 170, 245, 127, 213, 85, 85, 87, 255, 128, 7, 224, 127, 241, 85, 127, 255, 255, 0, 0, 0, 0, 0, 15, 239, 118, 145, 17, 17, 94, 219, 233, 132, 119, 236, 196, 135, 71, 152, 8, 152, 63, 195, 203, 219, 159, 199, 95, 47, 199, 125, 239, 191, 250, 76, 87, 43, 97, 239, 239, 251, 247, 232, 0, 32, 64, 0, 20, 4, 4, 60, 6, 0, 29, 7, 60, 225, 165, 85, 85, 69, 42, 170, 170, 170, 168, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 86, 170, 170, 254, 170, 170, 170, 170, 170, 170, 170, 170, 234, 170, 170, 168, 2, 170, 170, 170, 170, 191, 190, 62, 99, 255, 224, 216, 28, 24, 42, 171, 30, 119, 122, 175, 168, 64, 112, 125, 64, 11, 251, 250, 255, 193, 83, 84, 117, 112, 3, 0, 0], source: { file: "BLK71.SRC", label: "TDATA", line: 509 } },
  { name: "MTERR", encoding: 'stream', bytes: [37, 112, 7, 38, 119, 0, 38, 7, 112, 36, 7, 112, 35, 7, 112, 35, 112, 7, 36, 7, 112, 37, 112, 7, 38, 119, 0, 37, 7, 112, 36, 7, 112, 35, 7, 112, 33, 7, 112, 34, 112, 7, 36, 119, 0, 36, 112, 7, 38, 119, 0, 38, 119, 0, 37, 119, 0, 37, 112, 7, 38, 119, 0, 36, 7, 112, 35, 112, 7, 37, 119, 0, 38, 112, 7, 38, 119, 0, 38, 119, 0, 37, 7, 112, 35, 7, 112, 34, 7, 112, 33, 119, 0, 33, 112, 7, 35, 112, 7, 37, 112, 7, 37, 7, 112, 37, 119, 0, 37, 119, 0, 36, 119, 0, 34, 7, 112, 32, 7, 112, 30, 7, 112, 28, 7, 112, 29, 112, 7, 31, 112, 7, 33, 112, 7, 34, 112, 7, 36, 112, 7, 38, 112, 7, 38, 119, 0, 38, 119, 0, 38, 119, 0, 38, 119, 0, 38, 119, 0, 37, 119, 0, 37, 112, 7, 38, 119, 0, 36, 7, 112, 35, 119, 0, 36, 119, 0, 34, 7, 112, 35, 112, 7, 34, 7, 112, 33, 112, 7, 35, 112, 7, 37, 112, 7, 38, 119, 0, 38, 7, 112, 36, 7, 112, 35, 7, 112, 35, 112, 7, 36, 7, 112, 37, 112, 7, 38, 119, 0, 37, 7, 112, 36, 7, 112, 35, 7, 112, 33, 7, 112, 34, 112, 7, 36, 119, 0, 36, 112, 7, 38, 119, 0, 38, 119, 0, 37, 119, 0, 37, 112, 7, 38, 119, 0, 36, 7, 112, 35, 112, 7, 37, 119, 0, 38, 112, 7, 38, 119, 0, 38, 119, 0, 37, 7, 112, 35, 7, 112, 34, 7, 112, 33, 119, 0, 33, 112, 7, 35, 112, 7, 37, 112, 7, 37, 7, 112, 37, 119, 0, 37, 119, 0, 36, 119, 0, 34, 7, 112, 32, 7, 112, 30, 7, 112, 28, 7, 112, 29, 112, 7, 31, 112, 7, 33, 112, 7, 34, 112, 7, 36, 112, 7, 38, 112, 7, 38, 119, 0, 38, 119, 0, 38, 119, 0, 38, 119, 0, 38, 119, 0, 37, 119, 0, 37, 112, 7, 38, 119, 0, 36, 7, 112, 35, 119, 0, 36, 119, 0, 34, 7, 112, 35, 112, 7, 34, 7, 112, 33, 112, 7, 35, 112, 7], source: { file: "BLK71.SRC", label: "MTERR", line: 529 } },
]
