import { test } from 'node:test';
import assert from 'node:assert/strict';
import { toRomModels, emitTs } from '../../scripts/bake-models.mjs';

const OBJS = [{
  name: 'TIE', scale: 13,
  vertices: [[-130, -208, 234], [104, -208, 234], [182, -208, 0]],
  connect: [{ point: 0, draw: false }, { point: 1, draw: true }, { point: 2, draw: true }],
  anchorDropped: true, hasDrawList: true,
}];

test('toRomModels: derives edges from the connect list', () => {
  const [m] = toRomModels(OBJS);
  assert.equal(m.name, 'TIE');
  assert.deepEqual(m.edges, [[0, 1], [1, 2]]); // pen-up on 0 draws nothing
  assert.equal(m.hasDrawList, true);
});

test('toRomModels: an object with no draw list gets no edges', () => {
  const [m] = toRomModels([{ ...OBJS[0], name: 'PORT', connect: [], hasDrawList: false }]);
  assert.deepEqual(m.edges, []);
  assert.equal(m.hasDrawList, false);
});

test('emitTs: emits a DO-NOT-EDIT header and a typed ROM_MODELS export', () => {
  const ts = emitTs(toRomModels(OBJS));
  assert.match(ts, /GENERATED by scripts\/bake-models\.mjs/);
  assert.match(ts, /DO NOT EDIT/);
  assert.match(ts, /export const ROM_MODELS: readonly RomModel\[\]/);
  assert.match(ts, /name: 'TIE'/);
  assert.match(ts, /\[-130, -208, 234\]/);
});
