import { test } from 'node:test';
import assert from 'node:assert/strict';
import { toRomModels, emitTs } from '../../scripts/bake-models.mjs';

const OBJS = [{
  name: 'TIE', scale: 13,
  vertices: [[-130, -208, 234], [104, -208, 234], [182, -208, 0]],
  connect: [{ point: 0, draw: false }, { point: 1, draw: true }, { point: 2, draw: true }],
  anchorDropped: true, hasDrawList: true,
}];

test('toRomModels: derives edges from the connect list', () => {
  const [m] = toRomModels(OBJS);
  assert.equal(m.name, 'TIE');
  assert.deepEqual(m.edges, [[0, 1], [1, 2]]); // pen-up on 0 draws nothing
  assert.equal(m.hasDrawList, true);
});

test('toRomModels: an object with no draw list gets no edges', () => {
  const [m] = toRomModels([{ ...OBJS[0], name: 'PORT', connect: [], hasDrawList: false }]);
  assert.deepEqual(m.edges, []);
  assert.equal(m.hasDrawList, false);
});

test('emitTs: emits a DO-NOT-EDIT header and a typed ROM_MODELS export', () => {
  const ts = emitTs(toRomModels(OBJS));
  assert.match(ts, /GENERATED by scripts\/bake-models\.mjs/);
  assert.match(ts, /DO NOT EDIT/);
  assert.match(ts, /export const ROM_MODELS: readonly RomModel\[\]/);
  assert.match(ts, /name: 'TIE'/);
  assert.match(ts, /\[-130, -208, 234\]/);
});

// sw5-1 makes the old caveat FALSE. It said the ten ground objects' edges
// "are drawn by hand-coded PLOT/DRAWTO routines elsewhere in the assembly that
// this tool does not parse" — the tool parses them now. A stale caveat is worse
// than none: it tells a reader the artifact is missing data it actually has.
test('emitTs: the "edges not recoverable" caveat is GONE — the parser reads .WGD now', () => {
  const ts = emitTs(toRomModels(OBJS));
  assert.doesNotMatch(ts, /does not parse/i);
  assert.doesNotMatch(ts, /could not recover edge connectivity/i);
  assert.doesNotMatch(ts, /only VERTICES are authoritative/i);
});

// The caveat it is REPLACED by. Two ROM anomalies now survive into the baked
// edges, and a consumer that indexes `vertices[i]` blindly will read undefined
// on the second one — so the artifact has to say so, the way it already warns
// about degenerate self-edges.
test('emitTs: header documents WFG\'s out-of-range ROM stroke and tells consumers to filter it', () => {
  const ts = emitTs(toRomModels(OBJS));
  assert.match(ts, /\bWFG\b/, 'the anomaly must name the object');
  assert.match(ts, /vertices\.length/, '...and tell consumers the filter predicate');
  assert.match(ts, /self-edge/i, 'the existing degenerate-self-edge caveat must survive');
});
