import { test } from 'node:test';
import assert from 'node:assert/strict';
import { toRomPictures, emitPicturesTs } from '../../scripts/bake-models.mjs';
import { assembleRedBaronPictures } from '../../scripts/rom-models/redbaron-pictures.mjs';

const PICS = [{
  name: 'Plane (near)',
  points: [[0, 0, 40], [-16, 0, 40], [16, 0, 40]],
  connect: [{ point: 0, draw: false }, { point: 1, draw: true }, { point: 2, draw: true }],
}];

test('toRomPictures: derives edges from the connect list, keeps points+connect', () => {
  const [p] = toRomPictures(PICS);
  assert.equal(p.name, 'Plane (near)');
  assert.deepEqual(p.points, PICS[0].points);
  assert.deepEqual(p.connect, PICS[0].connect);
  assert.deepEqual(p.edges, [[0, 1], [1, 2]]); // pen-up on 0 draws nothing
});

test('toRomPictures: a picture with an empty connect list (COLLD) gets no edges', () => {
  const [p] = toRomPictures([{ name: 'Collision pts', points: PICS[0].points, connect: [] }]);
  assert.deepEqual(p.connect, []);
  assert.deepEqual(p.edges, []);
});

test('emitPicturesTs: emits a DO-NOT-EDIT header and a typed ROM_PICTURES export', () => {
  const ts = emitPicturesTs(toRomPictures(PICS));
  assert.match(ts, /GENERATED by scripts\/bake-models\.mjs/);
  assert.match(ts, /DO NOT EDIT/);
  assert.match(ts, /Re-generate with: just bake-models red-baron/);
  assert.match(ts, /export const ROM_PICTURES: readonly RomPicture\[\]/);
  assert.match(ts, /name: 'Plane \(near\)'/);
  assert.match(ts, /\[0, 0, 40\]/);
  assert.match(ts, /\{ point: 1, draw: true \}/);
});

test('emitPicturesTs: header explains COLLD\'s empty connect array and the near-zero-drift expectation', () => {
  const ts = emitPicturesTs(toRomPictures(PICS));
  assert.match(ts, /COLLD .*carries an EMPTY/);
  assert.match(ts, /connect\.length === 0/);
  assert.match(ts, /near-zero drift is the EXPECTED/);
});

test('emitPicturesTs output is byte-identical across repeated calls on the same input (idempotent)', () => {
  const models = toRomPictures(PICS);
  assert.equal(emitPicturesTs(models), emitPicturesTs(models));
});

// assembleRedBaronPictures: the PIECE0-3 quirk (redbaron-pictures.mjs's own
// header note) — a fabricated fixture standing in for 037007.XXX's
// PIECE0..PIECE3 block, which runs back-to-back with NO separating equate
// (PIECE1: sits directly ON a POINTP line). This pins the SLICE offsets
// (14, 23, 9, 9) against a small, controllable text instead of depending on
// the vendored ROM file (which the oracle test covers separately).
/** A `LABEL:\tPOINTP i,0,0\n\tPOINTP i+1,0,0\n...` block of `n` rows. */
function pointpTable(label, n) {
  let out = '';
  for (let i = 0; i < n; i++) {
    out += i === 0 ? `${label}:\tPOINTP ${i},0,0\n` : `\tPOINTP ${i},0,0\n`;
  }
  return out;
}

function fabricatedPieceFixture() {
  // program text needs a DB.PLN table with >= 29 rows so the drone slice(0,29)
  // stays well-formed; 42 rows mirrors the real ROM's plane table exactly.
  const program = `.RADIX 16\n${pointpTable('DB.PLN', 42)}.PLPNT\t=.-DB.PLN\n`;

  const pictures = `.RADIX 16
DB.MAP:\tBLANKV 0
\tVSBLEV 1
DB.MAR:\tBLANKV 0
\tVSBLEV 1
\tENDDB
DB.LNS:\tBLANKV 0
\tVSBLEV 1
\tENDDB
${pointpTable('DBPROP', 14)}.DBPRP\t=.-DBPROP
PPROPA:\tVSBLEV 1
\tENDDB
PPROPB:\tVSBLEV 1
\tENDDB
PPROPC:\tVSBLEV 1
\tENDDB
${pointpTable('COLLD', 4)}.COLLD\t=.-COLLD
${pointpTable('PIECE0', 14)}${pointpTable('PIECE1', 23)}${pointpTable('PIECE2', 9)}${pointpTable('PIECE3', 9)}PCDEC0:\tBLANKV 0
\tENDDB
PCDEC1:\tBLANKV 0
\tENDDB
PCDEC2:\tBLANKV 0
\tENDDB
${pointpTable('STAR0', 10)}.STAR0\t=.-STAR0
${pointpTable('STAR1', 12)}.STAR1\t=.-STAR1
DESTR0:\tBV 0
\tENDDB
DESTR1:\tBV 0
\tENDDB
${pointpTable('BLIMP', 36)}.BLMP\t=.-BLIMP
DBLIMP:\tBV 0
\tENDDB
`;
  return { program, pictures };
}

test('assembleRedBaronPictures: slices the PIECE0-3 combined run at (14, 23, 9, 9)', () => {
  const { program, pictures } = fabricatedPieceFixture();
  const pics = assembleRedBaronPictures(program, pictures);
  const byName = Object.fromEntries(pics.map((p) => [p.name, p]));

  assert.equal(byName['Piece 0'].points.length, 14);
  assert.equal(byName['Piece 1'].points.length, 23);
  assert.equal(byName['Piece 2'].points.length, 9);
  assert.equal(byName['Piece 3'].points.length, 9);
  // Piece 1's first point continues the combined run at offset 14 (index 0 in
  // its own fixture-local numbering, i.e. `POINTP 0,0,0` — same synthetic
  // shape repeats per piece in this fixture) — assert the SLICE boundary
  // itself by checking piece lengths sum to the whole combined run.
  const total = byName['Piece 0'].points.length + byName['Piece 1'].points.length +
    byName['Piece 2'].points.length + byName['Piece 3'].points.length;
  assert.equal(total, 55);
});

test('assembleRedBaronPictures: Piece 3 reuses PCDEC2 (PLPCDE\'s documented [0,1,2,2] mapping)', () => {
  const { program, pictures } = fabricatedPieceFixture();
  const pics = assembleRedBaronPictures(program, pictures);
  const byName = Object.fromEntries(pics.map((p) => [p.name, p]));
  assert.deepEqual(byName['Piece 2'].connect, byName['Piece 3'].connect);
});

test('assembleRedBaronPictures: Collision pts has an empty connect list (points-only ROM table)', () => {
  const { program, pictures } = fabricatedPieceFixture();
  const pics = assembleRedBaronPictures(program, pictures);
  const colld = pics.find((p) => p.name === 'Collision pts');
  assert.deepEqual(colld.connect, []);
  assert.equal(colld.points.length, 4);
});

test('assembleRedBaronPictures: Plane (near) concatenates DB.MAP+DB.MAR+DB.LNS; Plane (drone LOD) is DB.MAR alone over the first 29 points', () => {
  const { program, pictures } = fabricatedPieceFixture();
  const pics = assembleRedBaronPictures(program, pictures);
  const byName = Object.fromEntries(pics.map((p) => [p.name, p]));

  assert.equal(byName['Plane (near)'].points.length, 42);
  assert.equal(byName['Plane (near)'].connect.length, 2 + 2 + 2); // DB.MAP(2, stopAtLabel) + DB.MAR(2) + DB.LNS(2)
  assert.equal(byName['Plane (drone LOD)'].points.length, 29);
  assert.deepEqual(byName['Plane (drone LOD)'].connect, byName['Plane (near)'].connect.slice(2, 4)); // DB.MAR's own 2 ops
});

test('assembleRedBaronPictures throws (not silently mis-slices) when the PIECE0-3 combined run is the wrong length', () => {
  const { program } = fabricatedPieceFixture();
  // Drop PIECE3's rows entirely — the combined run is short.
  const brokenPictures = `.RADIX 16
DB.MAP:\tBLANKV 0
\tVSBLEV 1
DB.MAR:\tBLANKV 0
\tVSBLEV 1
\tENDDB
DB.LNS:\tBLANKV 0
\tVSBLEV 1
\tENDDB
DBPROP:\tPOINTP 0,0,0
.DBPRP\t=.-DBPROP
PPROPA:\tVSBLEV 1
\tENDDB
PPROPB:\tVSBLEV 1
\tENDDB
PPROPC:\tVSBLEV 1
\tENDDB
COLLD:\tPOINTP 0,0,0
.COLLD\t=.-COLLD
PIECE0:\tPOINTP 0,0,0
PCDEC0:\tBLANKV 0
\tENDDB
PCDEC1:\tBLANKV 0
\tENDDB
PCDEC2:\tBLANKV 0
\tENDDB
STAR0:\tPOINTP 0,0,0
.STAR0\t=.-STAR0
STAR1:\tPOINTP 0,0,0
.STAR1\t=.-STAR1
DESTR0:\tBV 0
\tENDDB
DESTR1:\tBV 0
\tENDDB
BLIMP:\tPOINTP 0,0,0
.BLMP\t=.-BLIMP
DBLIMP:\tBV 0
\tENDDB
`;
  assert.throws(
    () => assembleRedBaronPictures(program, brokenPictures),
    /PIECE0-3 combined run is 1 points, expected 55/,
  );
});
