// GENERATED by tools/bake-core-maze.mjs from the citation-gated
// reference/graphics/maze-vram.bin (MAME video RAM 0x4000-0x43ff); do not
// hand-edit. tests/core/maze-topology.test.ts re-derives this and asserts
// equality. wall/dot/energizer/path/tunnel are classified from the capture;
// the ghost HOUSE and GATE are stamped from ROM geometry (Dossier ch.3) —
// the attract capture over-paints the house with a GAME OVER banner. GPL
// firewall: nothing copied from shaunlebron/pacman.

/** The authentic 28x36 maze topology, one char per tile:
 *  '#' wall  '.' dot  'o' energizer  ' ' path  '=' gate  'H' house  'T' tunnel */
export const MAZE_ROWS: readonly string[] = [
  '############################',
  '############################',
  '############################',
  '############################',
  '#............##............#',
  '#.####.#####.##.#####.####.#',
  '#o####.#####.##.#####.####o#',
  '#.####.#####.##.#####.####.#',
  '#..........................#',
  '#.####.##.########.##.####.#',
  '#.####.##.########.##.####.#',
  '#......##....##....##......#',
  '######.##### ## #####.######',
  '######.##### ## #####.######',
  '######.##    ==    ##.######',
  '######.## #HHHHHH# ##.######',
  '######.## #HHHHHH# ##.######',
  'T     .   #HHHHHH#   .     T',
  '######.## #HHHHHH# ##.######',
  '######.## ######## ##.######',
  '######.##          ##.######',
  '######.## ######## ##.######',
  '######.## ######## ##.######',
  '#............##............#',
  '#.####.#####.##.#####.####.#',
  '#.####.#####.##.#####.####.#',
  '#o..##.......  .......##..o#',
  '###.##.##.########.##.##.###',
  '###.##.##.########.##.##.###',
  '#......##....##....##......#',
  '#.##########.##.##########.#',
  '#.##########.##.##########.#',
  '#..........................#',
  '############################',
  '############################',
  '############################',
]
