// Bakes the original Atari ROM source into a committed TypeScript artifact the
// contact sheet can import.
//
// WHY BAKE: the vendored source lives at ~/Projects/*-source-text and is in NO
// repo, so a browser page cannot import it. Same pattern as the existing
// star-wars/tools/pokey-bake and tools/speech-bake. The generated file IS the
// audit record.
//
// Usage:  node scripts/bake-models.mjs star-wars
//         just bake-models star-wars
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { homedir } from 'node:os';
import { parseWsobj } from './rom-models/wsobj.mjs';
import { connectToEdges } from './rom-models/derive.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const GAMES = {
  'star-wars': {
    source: join(homedir(), 'Projects', 'star-wars-1983-source-text', 'WSOBJ.MAC'),
    out: join(ROOT, 'star-wars', 'src', 'tools', 'romModels.generated.ts'),
    parse: parseWsobj,
  },
};

// --- pure core (unit-tested) -------------------------------------------------

/** Parsed ROM objects -> render-ready models (edges derived from the beam path). */
export function toRomModels(objs) {
  return objs.map((o) => ({
    name: o.name,
    scale: o.scale,
    vertices: o.vertices,
    edges: connectToEdges(o.connect),
    hasDrawList: o.hasDrawList,
  }));
}

const vec = (v) => `[${v.join(', ')}]`;

export function emitTs(models) {
  const body = models.map((m) => `  {
    name: '${m.name}',
    scale: ${m.scale},
    hasDrawList: ${m.hasDrawList},
    vertices: [${m.vertices.map(vec).join(', ')}],
    edges: [${m.edges.map(vec).join(', ')}],
  },`).join('\n');

  return `// GENERATED by scripts/bake-models.mjs — DO NOT EDIT.
// Re-generate with: just bake-models star-wars
//
// The authentic geometry from the original 1983 Atari source (WSOBJ.MAC):
// vertices from the .WP/.P/.PH tables, edges walked from the .WL draw lists.
// This is what the ROM actually drew — unlike src/core/models.ts, whose EDGES
// were reconstructed by heuristic because the disassembly held no draw lists.
//
// \`hasDrawList: false\` means the ROM has vertices but no .WL list for that
// object (PORT/WPN/WFF are drawn procedurally elsewhere) — its \`edges\` are
// empty and only its VERTICES are authoritative.
//
// Dev-tool data. Never import this from src/core — the core is the pure sim.

import type { Vec3 } from '@arcade/shared/math3d'

export interface RomModel {
  readonly name: string
  readonly scale: number
  readonly hasDrawList: boolean
  readonly vertices: readonly Vec3[]
  readonly edges: readonly (readonly [number, number])[]
}

export const ROM_MODELS: readonly RomModel[] = [
${body}
]
`;
}

// --- cli ---------------------------------------------------------------------

function main() {
  const game = process.argv[2];
  const cfg = GAMES[game];
  if (!cfg) {
    console.error(`usage: bake-models <${Object.keys(GAMES).join('|')}>`);
    process.exit(2);
  }
  if (!existsSync(cfg.source)) {
    console.error(`missing vendored source: ${cfg.source}`);
    console.error('run `just vendor-source-all` first');
    process.exit(1);
  }

  const models = toRomModels(cfg.parse(readFileSync(cfg.source, 'utf8')));
  mkdirSync(dirname(cfg.out), { recursive: true });
  writeFileSync(cfg.out, emitTs(models));

  const drawn = models.filter((m) => m.hasDrawList).length;
  console.log(`${game}: ${models.length} objects (${drawn} with draw lists) -> ${cfg.out}`);
  for (const m of models) {
    const note = m.hasDrawList ? `${m.edges.length} edges` : 'no draw list (vertices only)';
    console.log(`  ${m.name.padEnd(6)} ${String(m.vertices.length).padStart(3)} verts  ${note}`);
  }
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main();
}
