// Bakes the original Atari ROM source into a committed TypeScript artifact the
// contact sheet can import.
//
// WHY BAKE: the vendored source lives at ~/Projects/*-source-text and is in NO
// repo, so a browser page cannot import it. Same pattern as the existing
// star-wars/tools/pokey-bake and tools/speech-bake. The generated file IS the
// audit record.
//
// Usage:  node scripts/bake-models.mjs star-wars
//         just bake-models star-wars
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { homedir } from 'node:os';
import { parseWsobj } from './rom-models/wsobj.mjs';
import { connectToEdges } from './rom-models/derive.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const GAMES = {
  'star-wars': {
    source: join(homedir(), 'Projects', 'star-wars-1983-source-text', 'WSOBJ.MAC'),
    out: join(ROOT, 'star-wars', 'src', 'tools', 'romModels.generated.ts'),
    parse: parseWsobj,
  },
};

// --- pure core (unit-tested) -------------------------------------------------

/** Parsed ROM objects -> render-ready models (edges derived from the beam path). */
export function toRomModels(objs) {
  return objs.map((o) => ({
    name: o.name,
    scale: o.scale,
    vertices: o.vertices,
    edges: connectToEdges(o.connect),
    hasDrawList: o.hasDrawList,
  }));
}

const vec = (v) => `[${v.join(', ')}]`;

export function emitTs(models) {
  const body = models.map((m) => `  {
    name: '${m.name}',
    scale: ${m.scale},
    hasDrawList: ${m.hasDrawList},
    vertices: [${m.vertices.map(vec).join(', ')}],
    edges: [${m.edges.map(vec).join(', ')}],
  },`).join('\n');

  return `// GENERATED by scripts/bake-models.mjs — DO NOT EDIT.
// Re-generate with: just bake-models star-wars
//
// The authentic vertex geometry from the original 1983 Atari source
// (WSOBJ.MAC): vertices from the .WP/.P/.PH tables. Where a \`.WL\` draw list
// exists (hasDrawList: true), \`edges\` are walked from it — genuine ROM
// connectivity, unlike src/core/models.ts, whose edges were reconstructed by
// heuristic because the disassembly held no draw lists.
//
// IMPORTANT — \`hasDrawList: false\` (10 of 24 objects: GND, TWR, BNK, STB,
// WPN, WGA, WGB, WFF, WFG, PORT) does NOT mean the ROM draws these objects
// with no connecting lines. It means this parser could not recover edge
// connectivity for them from WSOBJ.MAC's .WL tables — they are drawn by
// hand-coded PLOT/DRAWTO routines elsewhere in the assembly that this tool
// does not parse. For these objects only VERTICES are authoritative; do not
// treat edges: [] as evidence the shipped game rendered a blank object.
//
// NOTE — \`edges\` is a faithful transcription of the ROM's beam path and may
// contain degenerate self-edges (\`[n, n]\`) where the draw list repeats an
// index (RTH has one: \`.BD 31,23,22,21,21,24,23\` walks to index 20 twice in a
// row, baked here as edge [20, 20]). A self-edge draws a zero-length line, not
// real connectivity — this artifact keeps it because the artifact is the
// audit record, but any consumer comparing or porting this geometry (edge
// diffing, hand-porting into src/core/models.ts) should filter \`a === b\`
// edges out first, the way romCompare.ts's \`isSelfEdge\` does.
//
// Dev-tool data. Never import this from src/core — the core is the pure sim.

import type { Vec3 } from '@arcade/shared/math3d'

export interface RomModel {
  readonly name: string
  readonly scale: number
  readonly hasDrawList: boolean
  readonly vertices: readonly Vec3[]
  readonly edges: readonly (readonly [number, number])[]
}

export const ROM_MODELS: readonly RomModel[] = [
${body}
]
`;
}

// --- cli ---------------------------------------------------------------------

function main() {
  const game = process.argv[2];
  const cfg = GAMES[game];
  if (!cfg) {
    console.error(`usage: bake-models <${Object.keys(GAMES).join('|')}>`);
    process.exit(2);
  }
  if (!existsSync(cfg.source)) {
    console.error(`missing vendored source: ${cfg.source}`);
    console.error('run `just vendor-source-all` first');
    process.exit(1);
  }

  const models = toRomModels(cfg.parse(readFileSync(cfg.source, 'utf8')));
  mkdirSync(dirname(cfg.out), { recursive: true });
  writeFileSync(cfg.out, emitTs(models));

  const drawn = models.filter((m) => m.hasDrawList).length;
  console.log(`${game}: ${models.length} objects (${drawn} with draw lists) -> ${cfg.out}`);
  for (const m of models) {
    const note = m.hasDrawList ? `${m.edges.length} edges` : 'no draw list (vertices only)';
    console.log(`  ${m.name.padEnd(6)} ${String(m.vertices.length).padStart(3)} verts  ${note}`);
  }
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main();
}
