// Bakes the original Atari ROM source into a committed TypeScript artifact the
// contact sheet can import.
//
// WHY BAKE: the vendored source (reference/atari-source/) is raw MACRO-11
// assembler text — a browser bundle cannot import it. Same pattern as the
// existing star-wars/tools/pokey-bake and tools/speech-bake. The generated file
// IS the audit record.
//
// Usage:  node scripts/bake-models.mjs star-wars
//         just bake-models star-wars
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { sourceDir } from './sources.mjs';
import { parseWsobj } from './rom-models/wsobj.mjs';
import { connectToEdges } from './rom-models/derive.mjs';
import { assembleRedBaronPictures } from './rom-models/redbaron-pictures.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

// Each entry names its vendored source file(s) (in-repo under
// reference/atari-source/ — see docs/reference-sources.md), the generated
// artifact it writes, and a `build`
// that turns the raw source text(s) into { code, lines } — the emitted
// TypeScript plus the human-readable per-object summary main() prints.
const GAMES = {
  'star-wars': {
    sources: [join(sourceDir('star-wars-1983'), 'WSOBJ.MAC')],
    out: join(ROOT, 'star-wars', 'src', 'tools', 'romModels.generated.ts'),
    build: (texts) => {
      const models = toRomModels(parseWsobj(texts[0]));
      const drawn = models.filter((m) => m.hasDrawList).length;
      const lines = [
        `star-wars: ${models.length} objects (${drawn} with draw lists)`,
        ...models.map((m) => {
          const note = m.hasDrawList ? `${m.edges.length} edges` : 'no draw list (vertices only)';
          return `  ${m.name.padEnd(6)} ${String(m.vertices.length).padStart(3)} verts  ${note}`;
        }),
      ];
      return { code: emitTs(models), lines };
    },
  },
  'red-baron': {
    sources: [
      join(sourceDir('red-baron'), 'RBARON.MAC'),
      join(sourceDir('red-baron'), '037007.XXX'),
    ],
    out: join(ROOT, 'red-baron', 'src', 'tools', 'romPictures.generated.ts'),
    build: (texts) => {
      const pictures = toRomPictures(assembleRedBaronPictures(texts[0], texts[1]));
      const lines = [
        `red-baron: ${pictures.length} pictures`,
        ...pictures.map((p) => {
          const note = p.connect.length === 0 ? 'no connect list (points only)' : `${p.edges.length} edges`;
          return `  ${p.name.padEnd(20)} ${String(p.points.length).padStart(3)} verts  ${note}`;
        }),
      ];
      return { code: emitPicturesTs(pictures), lines };
    },
  },
};

// --- pure core (unit-tested) -------------------------------------------------

/** Parsed ROM objects -> render-ready models (edges derived from the beam path). */
export function toRomModels(objs) {
  return objs.map((o) => ({
    name: o.name,
    scale: o.scale,
    vertices: o.vertices,
    edges: connectToEdges(o.connect),
    hasDrawList: o.hasDrawList,
  }));
}

const vec = (v) => `[${v.join(', ')}]`;

export function emitTs(models) {
  const body = models.map((m) => `  {
    name: '${m.name}',
    scale: ${m.scale},
    hasDrawList: ${m.hasDrawList},
    vertices: [${m.vertices.map(vec).join(', ')}],
    edges: [${m.edges.map(vec).join(', ')}],
  },`).join('\n');

  return `// GENERATED by scripts/bake-models.mjs — DO NOT EDIT.
// Re-generate with: just bake-models star-wars
//
// The authentic vertex geometry from the original 1983 Atari source
// (WSOBJ.MAC): vertices from the .WP/.P/.PH tables. \`edges\` are walked from
// the object's own ROM draw routine — genuine ROM connectivity, unlike
// src/core/models.ts, whose edges were reconstructed by heuristic because the
// disassembly held no draw lists.
//
// ALL 24 objects now carry real edges. Two kinds of draw routine exist and both
// are parsed: the interpretable \`.WL\` point-index list, and the ten ground
// objects' (GND, TWR, BNK, STB, WPN, WGA, WGB, WFF, WFG, PORT) direct-executing
// \`.WGD\` PLOT/DRAWTO/BDRAWTO routines. An earlier version of this artifact
// carried \`hasDrawList: false\` for those ten and warned that their edges were
// unrecoverable; that was wrong — the routines are pure macro calls over the
// same point tables, and they are read now.
//
// ⚠ THE ROM'S OWN OUT-OF-RANGE STROKE — WFG. WSOBJ.MAC:1844 draws \`DRAWTO 6,3\`,
// but WFG shares WFF's SIX-point table (indices 0..5): point 6 does not exist.
// On the real cabinet that reads a stale slot of the transform scratch page —
// an out-of-bounds read in the 1983 ROM, not a transcription error.
//
// What proves it is the ROM's bug and not our index rebase: across the other
// nine ground objects the lowest index used is exactly 0 and the highest is
// exactly \`vertices.length - 1\`. A rebase off by one in either direction breaks
// that immediately — too few and the minimum goes negative, too many and the
// maximum overruns. (The indices are not dense: BNK touches only 6 of its 15
// points. It is the ENDPOINTS that pin the rebase, not coverage.) WFF draws this
// very same six-point table and tops out at 5; only WFG reaches 6.
//
// It is transcribed verbatim rather than clamped, because this artifact is the
// audit record. So WFG's \`edges\` contain [5,6] and [6,3], whose index 6 is NOT a
// valid subscript of its \`vertices\`.
// ANY CONSUMER THAT WALKS \`edges\` INTO \`vertices[i]\` MUST SKIP EDGES WHOSE
// INDEX IS >= vertices.length — exactly as it must skip degenerate self-edges
// (below). Rendering one unfiltered strokes to \`undefined\`.
//
// NOTE — \`edges\` is a faithful transcription of the ROM's beam path and may
// contain degenerate self-edges (\`[n, n]\`) where the draw list repeats an
// index (RTH has one: \`.BD 31,23,22,21,21,24,23\` walks to index 20 twice in a
// row, baked here as edge [20, 20]). A self-edge draws a zero-length line, not
// real connectivity — this artifact keeps it because the artifact is the
// audit record, but any consumer comparing or porting this geometry (edge
// diffing, hand-porting into src/core/models.ts) should filter \`a === b\`
// edges out first, the way romCompare.ts's \`isSelfEdge\` does.
//
// Dev-tool data. Never import this from src/core — the core is the pure sim.

import type { Vec3 } from '@arcade/shared/math3d'

export interface RomModel {
  readonly name: string
  readonly scale: number
  readonly hasDrawList: boolean
  readonly vertices: readonly Vec3[]
  readonly edges: readonly (readonly [number, number])[]
}

export const ROM_MODELS: readonly RomModel[] = [
${body}
]
`;
}

/**
 * Parsed red-baron picture IR (`{name, points, connect}`) -> render-ready
 * pictures (edges derived from the connect-list beam path, same
 * `connectToEdges` walk `toRomModels` uses above). `connect` is kept
 * verbatim on the output — unlike star-wars's RomModel, a RomPicture carries
 * its connect-list too, because red-baron's port (topology.ts/biplane.ts)
 * stores ConnectOp lists, not raw edges, so romCompare.ts needs both to
 * derive the port's own edges the same way.
 */
export function toRomPictures(pics) {
  return pics.map((p) => ({
    name: p.name,
    points: p.points,
    connect: p.connect,
    edges: connectToEdges(p.connect),
  }));
}

const op = (o) => `{ point: ${o.point}, draw: ${o.draw} }`;

export function emitPicturesTs(pictures) {
  const body = pictures.map((p) => `  {
    name: '${p.name}',
    points: [${p.points.map(vec).join(', ')}],
    connect: [${p.connect.map(op).join(', ')}],
    edges: [${p.edges.map(vec).join(', ')}],
  },`).join('\n');

  return `// GENERATED by scripts/bake-models.mjs — DO NOT EDIT.
// Re-generate with: just bake-models red-baron
//
// The authentic vector-picture geometry from the original 1980 Atari source:
// vertex point-tables (\`POINTP\`) from the program ROM RBARON.MAC (the
// biplane's DB.PLN) and the picture ROM 037007.XXX — which IS RBPICS.MAC,
// misnamed by part number (the propeller, the four explosion-debris pieces,
// the two star-burst debris shapes, the blimp, and the plane's collision
// points). \`edges\` are walked from each picture's own ROM connect-list
// (\`BLANKV\`/\`VSBLEV\`) — genuine ROM beam-path connectivity, not a heuristic
// reconstruction.
//
// UNLIKE star-wars (whose port edges were RECONSTRUCTED by heuristic from
// vertex data alone, because no ROM draw list survived for many objects),
// red-baron's src/core/topology.ts and biplane.ts connect-lists were
// transcribed DIRECTLY from these same ROM tables (rb2-2, rb2-7, rb3-1
// findings). So this artifact — and the romCompare.ts drift check it feeds —
// is a DOUBLE-CHECK, not a first look: near-zero drift is the EXPECTED,
// unremarkable result. A genuine mismatch found here is a real transcription
// error worth reporting, not something to paper over by editing the port to
// match this generated file.
//
// COLLD ("Collision pts") carries an EMPTY \`connect\` array — 037007.XXX's
// COLLD table is a point-set only, with no ROM connect-list at all. A
// consumer must treat \`connect.length === 0\` as "points only, render as
// dots, never claim edge drift" — never fabricate connectivity for it.
//
// Dev-tool data. Never import this from src/core — the core is the pure sim.

import type { Vec3 } from '@arcade/shared/math3d'

export interface RomConnectOp {
  readonly point: number
  readonly draw: boolean
}

export interface RomPicture {
  readonly name: string
  readonly points: readonly Vec3[]
  readonly connect: readonly RomConnectOp[]
  readonly edges: readonly (readonly [number, number])[]
}

export const ROM_PICTURES: readonly RomPicture[] = [
${body}
]
`;
}

// --- cli ---------------------------------------------------------------------

function main() {
  const game = process.argv[2];
  const cfg = GAMES[game];
  if (!cfg) {
    console.error(`usage: bake-models <${Object.keys(GAMES).join('|')}>`);
    process.exit(2);
  }
  const missing = cfg.sources.filter((s) => !existsSync(s));
  if (missing.length > 0) {
    for (const s of missing) console.error(`missing vendored source: ${s}`);
    console.error('run `just vendor-source-all` first');
    process.exit(1);
  }

  const texts = cfg.sources.map((s) => readFileSync(s, 'utf8'));
  const { code, lines } = cfg.build(texts);
  mkdirSync(dirname(cfg.out), { recursive: true });
  writeFileSync(cfg.out, code);

  for (const line of lines) console.log(line);
  console.log(`  -> ${cfg.out}`);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main();
}
