// GENERATED by tools/bake-graphics.mjs from the citation-gated reference/graphics/*;
// do not hand-edit; that module's byte-equality test asserts equality against
// a fresh re-decode of the vendored ROM.
//
// Source PROMs: reference/graphics/82s123.7f (16 colours, resistor-DAC RGB)
// and reference/graphics/82s126.4a (256-entry colour-lookup, low nibble).
// Decode: src/shell/gfx-rom.ts (decodePaletteFromProm / decodeColourLookupFromProm).

/** The 16 hardware colours, decoded from 82s123.7f (MAME pacman_palette). */
export const HARDWARE_PALETTE: readonly (readonly [number, number, number])[] = [
  [0, 0, 0],
  [255, 0, 0],
  [222, 151, 81],
  [255, 184, 255],
  [0, 0, 0],
  [0, 255, 255],
  [71, 184, 255],
  [255, 184, 81],
  [0, 0, 0],
  [255, 255, 0],
  [0, 0, 0],
  [33, 33, 255],
  [0, 255, 0],
  [71, 184, 174],
  [255, 184, 174],
  [222, 222, 255],
]

/** 256-entry colour-lookup table from 82s126.4a: index by colorCode * 4 +
 * pixelValue, value is a palette index into HARDWARE_PALETTE. */
const COLOUR_LOOKUP: readonly number[] = [
  0, 0, 0, 0, 0, 15, 11, 1, 0, 0, 0, 0, 0, 15, 11, 3, 0, 0, 0, 0, 0, 15, 11, 5, 0, 0, 0, 0, 0, 15, 11, 7, 0, 0, 0, 0, 0, 11, 1, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 0, 14, 0, 1, 12, 15, 0, 14, 0, 11, 0, 12, 11, 14, 0, 12, 15, 1, 0, 0, 0, 0, 0, 1, 2, 15, 0, 7, 12, 2, 0, 9, 6, 15, 0, 13, 12, 15, 0, 5, 3, 9, 0, 15, 11, 0, 0, 14, 0, 11, 0, 14, 0, 11, 0, 0, 0, 0, 0, 15, 14, 1, 0, 15, 11, 14, 0, 14, 0, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
]

/** Palette index for a given colour code (0..63) and pixel value (0..3),
 * decoded from the 82s126.4a low nibble (MAME pacman colortable decode). */
export function colourLookup(colorCode: number, pixelValue: number): number {
  return COLOUR_LOOKUP[colorCode * 4 + pixelValue]
}
